---
title: "Equilibrium Uniqueness"
author: "Fabien Petit"
date: "17/06/2019"
output: 
  github_document:	
    pandoc_args: --webtex
---

```{r Initialization, include = FALSE}

# Load packages
packages <- c("dplyr", "ggplot2", "ggrepel", "RColorBrewer", "reshape2", "extrafont", "latex2exp")
lapply(packages, require, character.only = TRUE)
rm(packages)

# Graphic parameter
scale_graph = 1920/1080
red = brewer.pal(8, "Set1")[1]

```

## g function

The g function has four different shapes according to the value of $\sigma$ and both vertical asymptotes ($k_1$ and $k_2$). The function graphs are drawn using numerical computation with the following set of parameters for each case: a) $\sigma = 0.8$, $k_1 = 1$, $k_2 = 2$ ; b) $\sigma = 0.8$, $k_1 = 2$, $k_2 = 1$ ; c) $\sigma = 1.2$, $k_1 = 1$, $k_2 = 2$ ; d) $\sigma = 1.2$, $k_1 = 2$, $k_2 = 1$.

```{r g function - Define, include = FALSE}

g = function(k, sigma, ks){
  
  k1 = ks[1]
  k2 = ks[2]
  
  G = log((k/k1-1)/((k/k2)^((sigma-1)/sigma)-1))
  return(G)
}

```

```{r g function - Generate, include = FALSE, warning = FALSE}
# Interval vector
inter = seq(0, 10, length.out = 10000)

# 4 cases
sigmas = c(0.8, 1.2)
ks = list(c(1, 2), c(2,1))

# Empty data frame
df = data.frame(matrix(ncol = 5, nrow = 0)) %>% 
  setNames(c("inter", "sigma", "k1", "k2", "value"))

# Loop
for(i in c(1,2)){
  for(j in c(1,2)){
    
    df = cbind(inter, "sigma" = sigmas[i], "k1" = ks[[j]][1], "k2" = ks[[j]][2],
               "value" = g(inter, sigmas[i], ks[[j]])) %>% 
      as.data.frame() %>% 
      rbind(df)
    
  }
}
```

```{r}

df %>%
  mutate(k1 = factor(k1, labels = c(bquote(k[1] > k[2]), bquote(k[1] < k[2])))) %>% 
  
  ggplot(aes(x = inter, y = value)) +
  geom_line(size = 1, color = red) +
  geom_vline(xintercept = 1, linetype = "longdash", color = red, alpha = 0.5) +
  geom_vline(xintercept = 2, linetype = "longdash", color = red, alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "solid", color = "black") +
  facet_grid(sigma ~ k1 + k2, scales = "fixed",
             labeller = label_bquote(cols = paste(k[1] == .(k1), ", ", k[2] == .(k2)), 
                                     rows = sigma == .(sigma))
             ) +
  theme_classic(base_size = 14) +
  scale_x_continuous(name = bquote(k[t]), breaks = NULL, limits = c(0,5),
                     expand = c(0.001, 0)) +
  scale_y_continuous(name = bquote(g(k[t])), breaks = 0, limits = c(-1.5, 4.5)) +
  ggsave("gfunction_graph.png", width = 7, height = 7)


```


```{r}

# Second tentative with grid.arrange


df %>% subset(sigma == 0.8) %>% 
  ggplot(aes(x = inter, y = value)) +
  geom_line(color = red) +
  facet_wrap(. ~ k1, ncol = 1) +
  geom_vline(xintercept = 1, linetype = "longdash", color = red, alpha = 0.5) +
  geom_vline(xintercept = 2, linetype = "longdash", color = red, alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "solid", color = "black") +
  theme_classic(base_size = 14) +
  scale_x_continuous(name = bquote(k[t]), breaks = NULL, limits = c(0,3),
                     expand = c(0, 0)) +
  scale_y_continuous(name = bquote(g(k[t])), breaks = 0)

  
  
  
  
  
  
avg1 = ggplot(df[df$variable=="avg1",], aes(x=day, y=value)) +
  geom_bar(stat="identity") +
  facet_wrap(~variable) +
  coord_cartesian(ylim=c(300,500))

avg2 = ggplot(df[df$variable=="avg2",], aes(x=day, y=value)) +
  geom_bar(stat="identity") +
  facet_wrap(~variable) +
  coord_cartesian(ylim=c(3.5,8))

gridExtra::grid.arrange(avg1, avg2, ncol=2)

```



```{r g function - Generate, include = FALSE, warning = FALSE}
# Old version
df = cbind(inter, "sigma" = sigmas[1], "k[1]" = ks[[1]][1], "k[2]" = ks[[1]][2],
           "value" = g(inter, sigmas[1], ks[[1]])) %>% 
  as.data.frame() %>% 
  rbind(df)


df = data.frame("inter" = seq(0, 10, length.out = 10000))

# 4 cases
sigmas = c(0.8, 1.2)
ks = list(c(1, 2), c(2,1))

df = df %>% 
  mutate(g1 = g(inter, param$sigma[1], param$k1[1], param$k2[1]),
         g2 = g(inter, param$sigma[2], param$k1[2], param$k2[2]),
         g3 = g(inter, param$sigma[3], param$k1[3], param$k2[3]),
         g4 = g(inter, param$sigma[4], param$k1[4], param$k2[4]),) %>% 
  melt(id.vars = "inter")

```

### Case a)

```{r g Function - Graph a, echo = FALSE, warning = FALSE}

df %>%
  subset(variable == "g1") %>% 
  
  ggplot(aes(x = inter, y = value)) +
  geom_line(color = red) +
  # Dashed lines (specific values)
  geom_vline(xintercept = 1, color = red, linetype = "longdash", alpha = 0.5) +
  geom_vline(xintercept = 2, color = red, linetype = "longdash", alpha = 0.5) +
  # Axis
  scale_x_continuous(name = "", breaks = c(1, 2),
                     labels = c(TeX('$k_1$'),TeX('$k_2$')),
                     limits = c(0,3),
                     expand = c(0,0)) + 
  scale_y_continuous(name = "", breaks = c(0, 3.7),
                     labels = c(TeX('$0$'), TeX('$X_t$')),
                      limits = c(-1.5,3.5)) +
  # Graphic background
  coord_cartesian() + 
  theme_classic(base_size = 20) +
  theme(axis.line.x = element_blank(),
         axis.line = element_line(arrow = arrow(angle = 30, length = unit(0.4, "cm"), type = "open")),
         axis.ticks.x = element_blank(),
         axis.ticks.y = element_blank(),
         axis.text.x = element_text(color = red),
         axis.text.y = element_text(color = "black")) +
  annotate("segment", x = 0, xend = 2.97, y = 0, yend = 0,
           arrow = arrow(angle = 30, length = unit(0.4, "cm"), type = "open"), size = 1) +
  # Annotations
  annotate("text", x = 2.94, y = -0.2, label = TeX('$k_t$'), size = 6) +
  annotate("text", x = 1.5, y = 2.5, label = TeX('$g(k_t)$'), size = 5, col = "red") +
  # Save
  ggsave("graph_a.png", width = 7, height = 7)




```

### Case b)

```{r g Function - Graph b, echo = FALSE, warning = FALSE}

df %>%
  subset(variable == "g2") %>% 
  
  ggplot(aes(x = inter, y = value)) +
  geom_line(color = red) +
  # Dashed lines (specific values)
  geom_vline(xintercept = 1, color = red, linetype = "longdash", alpha = 0.5) +
  geom_vline(xintercept = 2, color = red, linetype = "longdash", alpha = 0.5) +
  # Axis
  scale_x_continuous(name = "", breaks = c(1,2), 
                     labels=c(TeX('$k_2$'),TeX('$k_1$')),
                     limits=c(0,3), expand = c(0,0)) +
  scale_y_continuous(name = "", breaks = c(0, 3.7),
                     labels = c(TeX('$0$'), TeX('$X_t$')),
                     limits = c(-1.5,3.5)) +
  # Graphic background
  coord_cartesian() + 
  theme_classic(base_size = 20) +
  theme(axis.line.x = element_blank(),
         axis.line = element_line(arrow = arrow(angle = 30, length = unit(0.4, "cm"), type = "open")),
         axis.ticks.x = element_blank(),
         axis.ticks.y = element_blank(),
         axis.text.x = element_text(color = red),
         axis.text.y = element_text(color = "black")) +
  annotate("segment", x = 0, xend = 2.97, y = 0, yend = 0,
           arrow = arrow(angle = 30, length = unit(0.4, "cm"), type = "open"), size = 1) +
  # Annotations
  annotate("text", x = 2.94, y = -0.2, label = TeX('$k_t$'), size = 6) +
  annotate("text", x = 1.5, y = 1.5, label = TeX('$g(k_t)$'), size = 5, col = "red") +
  # Save
  ggsave("graph_b.png", width = 7, height = 7)

```

### Case c)

```{r g Function - Graph c, echo = FALSE, warning = FALSE}

df %>%
  subset(variable == "g3") %>% 
  
  ggplot(aes(x = inter, y = value)) +
  geom_line(color = red) +
  # Dashed lines (specific values)
  geom_vline(xintercept = 1, color = red, linetype = "longdash", alpha = 0.5) +
  geom_vline(xintercept = 2, color = red, linetype = "longdash", alpha = 0.5) +
  # Axis
  scale_x_continuous(name = "", breaks = c(1,2),
                     labels = c(TeX('$k_1$'),TeX('$k_2$')),
                     limits = c(0, 10), expand = c(0,0)) +
  scale_y_continuous(name = "", breaks = c(0, 7.4),
                     labels = c(TeX('$0$'), TeX('$X_t$')),
                     limits = c(-3, 7)) +
  # Graphic background
  coord_cartesian() + 
  theme_classic(base_size = 20) +
  theme(axis.line.x = element_blank(),
         axis.line = element_line(arrow = arrow(angle = 30, length = unit(0.4, "cm"), type = "open")),
         axis.ticks.x = element_blank(),
         axis.ticks.y = element_blank(),
         axis.text.x = element_text(color = red),
         axis.text.y = element_text(color = "black")) +
  annotate("segment", x = 0, xend = 9.9, y = 0, yend = 0,
           arrow = arrow(angle = 30, length = unit(0.4, "cm"), type = "open"), size = 1) +
  # Annotations
  annotate("text", x = 9.8, y = -0.4, label = TeX('$k_t$'), size = 6) +
  annotate("text", x = 4, y = 2.5, label = TeX('$g(k_t)$'), size = 5, col = "red") +
  # Save
  ggsave("graph_c.png", width = 7, height = 7)

```

### Case d)

```{r g Function - Graph d, echo = FALSE, warning = FALSE}

df %>%
  subset(variable == "g4") %>% 
  
  ggplot(aes(x = inter, y = value)) +
  geom_line(color = red) +
  # Dashed lines (specific values)
  geom_vline(xintercept = 1, color = red, linetype = "longdash", alpha = 0.5) +
  geom_vline(xintercept = 2, color = red, linetype = "longdash", alpha = 0.5) +
  # Axis
  scale_x_continuous(name = "", breaks = c(1,2),
                     labels = c(TeX('$k_2$'),TeX('$k_1$')),
                     limits = c(0, 10), expand = c(0,0)) +
  scale_y_continuous(name = "", breaks = c(0, 7.4),
                     labels = c(TeX('$0$'), TeX('$X_t$')),
                     limits = c(-3, 7)) +
  # Graphic background
  coord_cartesian() + 
  theme_classic(base_size = 20) +
  theme(axis.line.x = element_blank(),
         axis.line = element_line(arrow = arrow(angle = 30, length = unit(0.4, "cm"), type = "open")),
         axis.ticks.x = element_blank(),
         axis.ticks.y = element_blank(),
         axis.text.x = element_text(color = red),
         axis.text.y = element_text(color = "black")) +
  annotate("segment", x = 0, xend = 9.9, y = 0, yend = 0,
           arrow = arrow(angle = 30, length = unit(0.4, "cm"), type = "open"), size = 1) +
  # Annotations
  annotate("text", x = 9.8, y = -0.4, label = TeX('$k_t$'), size = 6) +
  annotate("text", x = 4, y = 2.5, label = TeX('$g(k_t)$'), size = 5, col = "red") +
  # Save
  ggsave("graph_d.png", width = 7, height = 7)

```

```{r Facet wrap}


```


## h function

### Case 1)

### Case 2)

### Case 3)

## Uniqueness in case c)

```{r Uniqueness in case c, echo = FALSE, warning = FALSE}
# Ranges
sigma_range = c(1.1, 1.2, 1.3, 1.5, 1.7)
k1 = 1
k2_range = c(1.01, 1.5, 2)

# Interval
inter = seq(0.001, 30, 0.001)

# Empty data frame
result = data.frame(matrix(ncol = 4, nrow = 0)) %>% 
  setNames(c("inter", "sigma", "k2", "value"))

# Loop to compute g function
for(k2 in k2_range){
  for(sigma in sigma_range){
   
   g = function(k, sigma, k1, k2){
      G = log((k/k1-1)/((k/k2)^((sigma-1)/sigma)-1))
      return(G)
   }
   
   result = cbind(inter, sigma, k2, "value" = g(inter, sigma, k1, k2)) %>% 
     rbind(result)
   
  }
}

result = as.data.frame(result)

# Compute bound and violation logic
result = result %>% 
  subset(inter > k2) %>% 
   mutate(bound = 1/as.numeric(as.character(sigma)),
          violation = ifelse(bound > value, TRUE, FALSE),
          sigma = as.factor(sigma),
          k2 = as.factor(k2))

# Check if g and h intersect
sum(result$violation, na.rm = TRUE) # If =  0, then do not intersect after k2
```


```{r Uniqueness in case c - Min values, echo = FALSE, warning = FALSE}
# Show minimum k on (k2, +infinity)
min_val = result %>%  
  group_by(sigma, k2) %>% 
  summarise(min(value), min(bound)) %>% 
  setNames(c("sigma", "k2", "min_k", "min_x"))
min_val
```


```{r Uniqueness in case c - Graph, echo = FALSE, warning = FALSE}
x_bound = min_val %>% pull("min_x")

result %>%  
  
  ggplot(aes(x = inter, y = value)) +
  geom_line(aes(color = sigma)) +
  geom_hline(data = min_val, aes(yintercept = x_bound, color = sigma), linetype = "dashed") +
  facet_wrap(k2 ~ ., labeller = label_bquote(alpha == .(as.numeric(as.character(k2))))) +
  scale_x_continuous(breaks = 0, limits = c(0, 10), expand = c(0,0)) +
  scale_y_continuous(breaks = c(0,1), limits = c(0, 5), expand = c(0,0)) +
  scale_color_manual(name = bquote(sigma), values = brewer.pal(8, "Set1")) +
  theme_classic(base_size = 14) +
  theme(legend.position = "right") +
  labs(x = bquote(tilde(k)[t]), y = "") +
  ggsave("sigma_k2.png", width = scale_graph*5, height = scale_graph*5/3)

```

