--- 
title: "Intergenerational conflict and the declining labor share"
author:
  - "Fabien Petit^[Aix-Marseille University, CNRS, EHESS, Centrale Marseille, AMSE. Contact: Aix-Marseille School of Economics, 5-9 Boulevard Maurice Bourdet, 13001 Marseille, France. Email: fabien.petit@univ-amu.fr. Website: [fabienpetit.com](https://www.fabienpetit.com)]"
thanks: "I am grateful to Cecilia García-Peñalosa, Marc Sangnier, Frédéric Dufourt and Céline Poilly. This work was supported by French National Research Agency Grants ANR-17-EURE-0020."
date: "`r Sys.Date()`"
keywords: "Labor share, Inter-generational conflict, Wage bargaining, Probabilistic voting."
site: bookdown::bookdown_site
documentclass: article
link-citations: yes
bibliography: lisa.bib
biblio-style: apalike
description: "This is the first paper of my thesis."
always_allow_html: true
---
```{r, include = FALSE}
# Load init script
source("_script/init.R")
# knitr options
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
options(kableExtra.html.bsTable = T)
```

`r if(knitr::is_html_output())
'# Preface {-}'
`
`r if(knitr::is_html_output()) 
'## Abstract {-}'
`

`r if(knitr::is_latex_output())
'\\begin{abstract}'
`
A large literature has studied multiple determinants of the labor share, but the age structure of the population has received little attention. This paper argues that demographic dynamics in high-income countries affect the labor share in two different ways: directly through the labor supply and the capital accumulation, and indirectly through public policy. I use an OLG model in which a generation conflict arises because young and old individuals have different income sources and opposite objectives in terms of public policy. The youth face an unemployment risk and use their political power to raise the unemployment benefits. This fight over the public budget allocation has consequences for wage bargaining and thus for the labor share. Numerical simulations for France and the United-States indicate that the model can replicate the data and that baby-boomers’ cohorts have driven the labor share dynamics.
`r if(knitr::is_latex_output())
'\\end{abstract}'
`
`r if(knitr::is_html_output()) 
'## Acknowledgments {-}'
`
`r if(knitr::is_html_output()) 
'I am grateful to Cecilia García-Peñalosa, Marc Sangnier, Frédéric Dufourt and Céline Poilly. This work was supported by French National Research Agency Grants ANR-17-EURE-0020.'
`

`r if(knitr::is_latex_output())
'\\clearpage\\doublespacing'
`