% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Intergenerational conflict and the declining labor share},
  pdfauthor={Fabien Petit},
  pdfkeywords={Labor share, Inter-generational conflict, Wage bargaining, Probabilistic voting.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{geometry}
\usepackage{booktabs}
\usepackage{threeparttable}
\usepackage{setspace}
\usepackage{caption}
\usepackage{ragged2e}
\usepackage{dcolumn}
\usepackage{floatrow}
\floatsetup[figure]{capposition=top}
\usepackage[fontsize=12pt]{scrextend}
\interfootnotelinepenalty=10000

\onehalfspacing

\newtheorem{theorem}{Theorem}
\newtheorem{corollary}[theorem]{Corollary}
\newtheorem{proposition}{Proposition}
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{conjecture}{Conjecture}
\newenvironment{proof}[1][Proof]{\noindent\textbf{#1.} }{\ \rule{0.5em}{0.5em}}

% Vertical spacing in table
\renewcommand{\arraystretch}{1} % Default value: 1

\newcommand{\red}[1]{{\color{red} #1}}
\newcommand{\blue}[1]{{\color{blue} #1}}

\newcolumntype{L}[1]{>{\raggedright\let\newline\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{C}[1]{>{\centering\let\newline\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{R}[1]{>{\raggedleft\let\newline\\arraybackslash\hspace{0pt}}m{#1}}

\geometry{left = 1.0in, right = 1.0in, top = 1.0in , bottom = 1.0in}
\setlength\parindent{24pt}

\hypersetup{
	colorlinks = true,
	linkcolor = blue,
	anchorcolor = blue,
	citecolor = blue,
	filecolor = blue,
	urlcolor = blue
}
\usepackage[]{natbib}
\bibliographystyle{apalike}

\title{Intergenerational conflict and the declining labor share\thanks{I am grateful to Cecilia García-Peñalosa, Marc Sangnier, Frédéric Dufourt and Céline Poilly. This work was supported by French National Research Agency Grants ANR-17-EURE-0020.}}
\author{Fabien Petit\footnote{Aix-Marseille University, CNRS, EHESS, Centrale Marseille, AMSE. Contact: Aix-Marseille School of Economics, 5-9 Boulevard Maurice Bourdet, 13001 Marseille, France. Email: \href{mailto:fabien.petit@univ-amu.fr}{\nolinkurl{fabien.petit@univ-amu.fr}}. Website: \href{https://www.fabienpetit.com}{fabienpetit.com}}}
\date{2020-05-04}

\let\BeginKnitrBlock\begin \let\EndKnitrBlock\end
\begin{document}
\maketitle

\begin{abstract}
A large literature has studied multiple determinants of the labor share, but the age structure of the population has received little attention. This paper argues that demographic dynamics in high-income countries affect the labor share in two different ways: directly through the labor supply and the capital accumulation, and indirectly through public policy. I use an OLG model in which a generation conflict arises because young and old individuals have different income sources and opposite objectives in terms of public policy. The youth face an unemployment risk and use their political power to raise the unemployment benefits. This fight over the public budget allocation has consequences for wage bargaining and thus for the labor share. Numerical simulations for France and the United-States indicate that the model can replicate the data and that baby-boomers’ cohorts have driven the labor share dynamics.
\end{abstract}

\clearpage\doublespacing

\hypertarget{intro}{%
\section{Introduction}\label{intro}}

The labor income share is often assumed as constant by the economists. However, it has decreased during the last decades in OECD countries as emphasized by \citet{Karabarbounis2014}.
\citet{Caballero1998} show that firms substitute labor with capital through biased technical change to thwart workers empowerment.
At the same time, high-income countries such as France and the United States have experienced a population aging related to the existence of the larger cohort of the \emph{baby-boomers}.
Yet, the literature has paid little attention to the impact of population dynamics on the labor share.
Moreover, variations of the demographic structure may also affect public policy by changing welfare state preferences. Many authors have shown the existence of inter-generational conflicts over public budget allocation \citep[see, for example,][]{Busemeyer2009, Sorensen2013}.
Public policy determines labor market institutions which are key determinants of wage and employment and therefore the labor share. Thus, the shift away from labor toward capital may be due to labor market institutions endogenously determined by the age structure of the population.
To the best of my knowledge, this paper is the first to investigate the long-run relationship between the demographic dynamics and the labor share through the inter-generational conflict.

I start by presenting a theoretical framework which links the age structure of the population to the labor share. I use a two-period overlapping generations (OLG) model with two types of individuals: young and old. Young individuals supply labor and earn a labor income while old households earn capital income, the return of their savings.
The government levies taxes on both incomes and uses them to provide unemployment benefits and fund health spending on the elderly. The public budget allocation is a source of age-related conflict because any welfare improvement for a generation is done at the expense of the other generation. Public policy is endogenous and determined through voting. The larger is a generation with respect to the other, the stronger is its political power and therefore the closer to its desired public policy is this generation. Youth desire more redistribution and unemployment benefits.
Meanwhile, the representative labor union bargains with the representative firm over wages. The out-of-work options of young agents are positively affected by the level of unemployment benefits but negatively by the tax rate. These options enable the representative union to bargain greater wages. However, greater wages reduce the labor demand of the representative firm and thus increases the capital-per-worker and output-per-worker. The labor share can be defined as the ratio between the wage rate and output-per-worker. Consequently, the effect of greater wages on the labor share depends on the value of the capital-labor elasticity of substitution.
The equilibrium is determined by the interaction of the voting and the wage bargaining. The total effect of demographic dynamics on the labor share passes through three variables: the capital stock determined by the savings of the previous young generation; the labor supply which is taken into account in the wage bargaining; and the youth political power that defines the level of the out-of-work option and thus the ability of workers to increase their wages. However, the total effect is ambiguous and depends on parameter values.

To deal with the ambiguity of the qualitative effect, I provide a quantitative analysis for France and the United-States. The calibration of the parameters leads to an elasticity of substitution between capital and labor greater than one. Thus, both input factors are gross substitutes, meaning that firms are able to substitute labor with capital for a given level of output. The model is able to replicate the data over the last decades and predicts a slight rise of the labor share due to the aging of the baby-boomers' cohort. This cohort drives the public policy agenda and hence the labor share. When the baby-boomers are young, their massive entrance in the labor market increases the labor supply. They also shape institutions in their favor through the voting process, leading to greater wages. As a response, firms shift away from labor toward capital to thwart the workers' ability to grab part of the income. Thus, the labor share declines. Once this generation becomes old, the mechanism is reversed. However, the expected increase in the labor share is dampened by the capital accumulation fostered by the extensive savings of the baby-boomers.

I also quantify the role of each determinant and channel.
Demographic dynamics are determined by the population growth and the survival rate, i.e.~the life expectancy. The rising survival rate is the dominant explanatory factor in both countries. Then, the age structure of the population affects the labor share in two different ways: directly through the labor supply and the capital accumulation, and indirectly through the endogenous public policy. Model predictions suggest that the indirect channel should play a considerable role in the next decades due to the retirement of the baby-boomers.

Lastly, two aspects are worth noting. First, even though baby-boomers appear as income losers over the last decades because the labor share has fallen, they were actually the winners once net income is considered due to the implementation of a redistributive public policy. Once they retire, they are still the winners of public budget allocation's inter-generational conflict because the mechanism works the other way around.
Second, I find that an increase of the retirement age in the next decades should lead to a decline of the labor share due to capital over-accumulation.
Young agents expected to remain longer retired and therefore saved more, leading to an over-accumulation of capital. At the same time, the youth's political power increases and so does the wage. Thus, the firm substitute labor with capital. However, once the capital comes back to its optimal accumulation path, so in the very long-run, the labor share increases.

This paper is related to the extensive literature on the labor share \citep[see, for example,][]{Blanchard1997, Caballero1998, Acemoglu2003, Karabarbounis2014, Autor2019}. Multiple determinants have been analyzed by economists to explain its decline over the past decades, notably the role of institutions and the biased technical change.\footnote{Although the globalization has also recently received sizable research interest as a determinant of the labor share \citetext{\citealp[see, for example,][]{Jayadev2007}; \citealp{Pica2010}; \citealp{Young2018}; \citealp[and][]{Autor2019}}.}
The institutional context argument was first put forward by \citet{Blanchard1997} to explain the persistence of shocks to the labor market. In principle, the adverse supply shocks of the 1970s should have had an impact on employment and the labor share only in the short run. Due to labor market institutions, such as adjustment costs, these shocks generated long lags in labor demand and thereby their persistence in the long-run.
In addition to adjustment costs, \citet{Bentolila2003} also highlight the role of workers' bargaining power to explain the gap between the marginal product of labor and the wage.
These pro-labor income institutions are a burden to firms because they limit the firms' ability to optimize input factors' allocation but also because they enable the workers to obtain a high income share in the short-run. \citet{Caballero1998} incorporate the long-run response of firms in order to thwart workers empowerment. This response is the substitution of labor with capital through biased technical change.\footnote{\citet{Acemoglu2002} shows that factor abundance and factor prices are key determinants of the direction toward which factor the technical change is biased. In line with this result, \citet{Karabarbounis2014} show that the decrease in the relative price of investment goods induced firms to shift away from labor and toward capital.}
Others have developed models with factor-saving innovation \citep[see, for example,][]{Zuleta2008, Peretto2013}.
I do not incorporate any biased technical change in the model in order to analyze the role of the demographic dynamics. I show that the model is able to replicate labor share's dynamics without biased technical change. Therefore, it suggests that biased technical change may be the firms' response to the workers empowerment fostered by changes in the age structure of the population. I use the argument developed by \citet{Caballero1998} by looking at an upstream step to determine the reasons of such a labor market institutional context. I claim that labor market institutions are the result of the aggregation of public policy preferences. Therefore, the age structure of the population does matter to explain the dynamics of the labor share.

An interest in the impact of demographic dynamics on economic variables is not new. Many authors have looked at it at the micro and macro-levels.\footnote{see \citet{Clark1978} for a survey; and \citet{Bloom2016} for a recent survey of the determinants of population aging.}
This phenomenon presents serious challenges in many fields of the economy. Some authors have examined its impact on economic growth \citep[see][]{VanGroezen2005, Soares2005, Bloom2010, Lee2010}. Others have investigated the sustainability of pension systems in such a context \citep[see][]{Ono2003, DelaCroix2013, Philipov2014} and discussed the optimality and feasibility of pension reforms \citep[see][]{Pecchenino1997, Sinn2003}. Related to the pension issue, the legal age of retirement is also probed \citep[see][]{Futagami2001, Dedry2017}. Despite the existing literature on population aging, the impact on the income allocation between capital and labor has been understudied. To the best of my knowledge, \citet{Schmidt2013} is the only existing paper looking at the impact of population aging on the labor share. They use an OLG model with a pension system to show that an aging population leads to more saving and hence more capital. For a capital-labor elasticity of substitution greater (resp. smaller) than unity, the effect on the labor share is negative (resp. positive). Their paper points out a link between the population aging and the labor share through capital accumulation.\footnote{They also show that population aging reduces the labor share in a small economy with perfect capital mobility, regardless of the value of capital-labor elasticity of substitution. Households invest abroad because domestic interest rates fall. As a result, the increasing net foreign assets income shrinks the labor share.} My paper includes this mechanism and reaches the same conclusions on it. However, I add a new mechanism through the inter-generational conflict over public budget allocation and show that it accounts for more than the half of the dynamics.

This paper relies on recent empirical studies showing that public policy preferences are likely to change over the life-cycle. Because the youth and the elderly do not benefit from the same public policy instruments nor have the same income sources \citep[see, for example,][]{Busemeyer2009, Sorensen2013}.\footnote{\citet{Sorensen2013} uses cross-sectional survey data for 22 countries from four Role of Government surveys (1985, 1990, 1996 and 200) of the International Social Survey Program (ISSP).} He shows that elderly people desire less spending in education while they are in support of more in health and pension. But he claims that these life-cycle effects are quite small. \citet{Busemeyer2009} use cross-sectional survey data for 14 OECD countries from the 1996 ISSP Role of Government dataset. On the contrary, they find sizable age-related differences in public policy preferences. Although these studies disagree on the magnitude of the conflict, they all claim that such a conflict does exist. They also agree on the magnitude heterogeneity across countries. \citet{Jager2016} find a negative long-run relationship between population aging and public investment because older individuals discount more future payoffs with respect to young individuals.\footnote{\citet{Jager2016} use panel data of 19 OECD countries between 1971 and 2007. See also, \citet{Harrison2002}; \citet{Read2004}, for estimations of discount rates. It is also worth mentioning the recent empirical study of \citet{Huffman2017} in which they decompose the characteristics of time discounting in old population.}
I make use of recent findings on life-cycle public policy preferences to generate an inter-generational conflict over the public budget allocation. For simplicity, I summarize it on two dimensions: the unemployment benefits and the health spending. Although the unemployment benefits are necessary to generate an interaction with the labor market through the wage bargaining. Health spending could be replaced by any type of government spending that benefits the elderly.

This paper also relates to the literature on politico-economic models. This literature follows the work of \citet{Lindbeck1987} on probabilistic voting. These models are useful to examine the relationship between redistribution policies and growth.\footnote{See, for example, \citet{Alesina1994}; \citet{Persson1994}; \citet{Krusell1997}.} The first models were rather focused on intra-generational government budget allocation conflicts, while recent papers such as \citet{Lancia2012} are concerned with inter-generational conflicts. \citet{Lancia2012} develop a politico-economic equilibrium model in which aging has two opposite effects on growth. On one hand, it generates incentives for human capital accumulation and innovation, on the other, it increases the political weight of the elderly who are against innovation and makes policies more difficult to implement.\footnote{Their OLG model has three types of agents: young, adult and old. The economic growth is determined by two components: human capital growth and total factor productivity growth. First, young agents inherit the average human capital level of their parents and decide to invest on their education level. The higher is the expected life expectancy, the greater is the incentive to educate. Investing in education increases human capital. Second, all agents vote to determine the innovation public policy that fosters total factor productivity. This investment is done at the cost of public pensions. Thus, elderly are necessary opposed to innovation. When both, young and adults, are net winners from public investment policy, they form a coalition in the political process to adopt such a policy.}
With the same type of conflict on transfers to retired old households and public investment, \citet{Gonzalez-Eiras2012} analyze implications for per-capita growth.\footnote{However, they also endogenize the retirement age in a politico-economic equilibrium.} My approach is closely linked to theirs but applied to the labor share. They distinguish two effects: a direct one through the savings rate, labor supply and capital accumulation, and an indirect one through the age-related conflict to determine taxes, government spending and the retirement age. They predict an increase in the tax rate and the retirement age in OECD countries to offset population aging which should boost per-capita growth. I use the same decomposition into the direct and indirect channels. I also decompose the aging of population in the decline in population growth and the increase in the survival rate, i.e.~the life-expectancy.
I show that the age structure of the population affects factor shares. Yet, most of the papers that look at the impact of population aging on the economic growth use a Cobb-Douglas production function where factor shares are constant. Therefore, I suggest that some conclusions should be reconsider inline with this mechanism.

The two main hypothesis of the paper are about the elasticity of substitution between capital and labor and the right-to-manage specification for the wage bargaining. Recent estimates suggest that this elasticity may be greater than one \citep[see][]{Karabarbounis2014}\footnote{\citet{Caballero1998} also use a relatively high value of the capital-labor elasticity of substitution, about 6.00, to simulate French data.} but an other part of the literature has found it below one, particularly for the United-States \citep[see, for example,][]{Antras2004, Chirinko2008}.
Moreover, I do not include any form of biased technical change within the model. This is voluntary in order to develop an other theory on the labor share's decline based on demographic dynamics. It could be the case that biased technical change is also driven by demographic dynamics through the \emph{grability} of workers to seize part of the rent. This grability may be generated by some cohorts which are sufficiently numerous to shape labor market institutions in their favor and therefore in favor of labor.

The paper is organized as follows. Section \ref{model} presents the theoretical framework. Section \ref{quantitative} provides the quantitative analysis. It starts with the analysis of the model's predictions and mechanisms. I then perform an aging-effect decomposition with counterfactual simulations. Section \ref{discussion} discusses some results of the paper. Section \ref{conclusion} concludes.

\hypertarget{model}{%
\section{Model}\label{model}}

I consider a two-period OLG model in which there are two types of individuals: young and old. The economy is closed and capital fully depreciates between two periods.
Agents vote to establish the public policy through probabilistic voting. Public policy, and more specifically labor market institutions, impact wage bargaining between the representative firm and the representative union.
While at the same time, the representative union bargains over wages with the representative firm. The outcome of the bargaining, i.e.~the wage rate, determines the level of employment and thus the tax base to fund public policy.
Both processes are independent and simultaneous, hence they jointly determine the equilibrium of the economy and therefore the labor share.
Thus, I assume that there is no coordination between households and the labor union. Households cannot synchronize their vote with the action of the representative union, neither the opposite. Therefore, the agents who operate within the wage bargaining take the voting outcome as given and vice versa.

\hypertarget{households}{%
\subsection{Households}\label{households}}

The demographic dynamic of young households is \(N^y_t = n_t N^y_{t-1}\) with \(n_t > 0\) the gross young population growth. While the demographic dynamic of old households is \(N^o_t = p_t N^y_{t-1}\) with \(p_t \in \left(0,1\right]\) the survival rate.\footnote{The survival rate \(p_t\) is an increasing function of the life expectancy and a decreasing function of the retirement age. In the model, agents are considered as old once they retire. If the life expectancy and the retirement age grow at the same rate, then the survival rate remains constant. For more details on the measurement of population aging, see \citet{Sanderson2007}; \citet{Sanderson2013}; \citet{DAlbis2013}.} Both demographic parameters follow deterministic processes. Thus, the old-age dependency ratio is \(N^o_t/N^y_t = p_t/n_t\). The whole population is therefore \(N_t = N^y_t + N^o_t\).

Each cohort consists of a continuum of agents with identical preferences. Young households in period \(t\) supply labor inelastically, earn a net income, consume and save for retirement. They face an idiosyncratic longevity risk: with probability \(p_{t+1}\) they survive to become old households in period \(t+1\). Once old, they pay taxes on their saving returns, consume and derive utility from government health spending. Finally, old households die at the end of the period. Savings of young agents who die before reaching old age are distributed among their surviving peers, reflecting a perfect annuities market.

Households derive utility from consumption when young \(c_{1,t}\) and old \(c_{2,t+1}\). Once old, they also value government health expenditure \(h_{t+1}\). Agents discount the future at factor \(\alpha \in \left(0,1\right)\). Due to risk of death, the effective discount factor of young households equals \(\alpha p_{t+1}\).\footnote{Since the expected survival rate \(p_{t+1}\) is an increasing function of the expected life expectancy. The longer an agent expects to live, the less they discounts future.} I assume that period utility functions are logarithmic. In first period, they earn a net income \(y_t\) to allocate between consumption and savings \(s_t\). In second period, they consume the net return of their savings \((1-\tau_{t+1}) s_t \hat{R}_{t+1}\), where \(\tau_{t+1}\) is the tax rate and \(\hat{R}_{t+1}\) the gross return on savings of a young household that survives to old age\footnote{Due to perfect annuity market \(\hat{R}_t = R_t/p_t\) where \(R_t\) is the gross return on physical capital.}. Maximizing expected utility, a household in period \(t\) solves the following maximization problem:
\begin{align*}
  \max_{c_{1,t},~c_{2,t+1}} &\ln c_{1,t} + \alpha p_{t+1}\left( \ln c_{2,t+1} + \beta \ln h_{t+1} \right)\\
    \text{s.t.} ~~ & \begin{cases}
    c_{1,t} + s_t = y_t \\
    c_{2,t+1} = (1-\tau_{t+1}) s_t \hat{R}_{t+1}
    \end{cases}
\end{align*}
where \(\beta>0\) characterizes the preference for health expenditure. Solving the household maximization problem, I obtain the optimal consumption in both period and savings in first period for a household of type \(i \in \lbrace e, u \rbrace\):
\begin{align*}
  c^i_{1,t} &= \frac{1}{1+\alpha p_{t+1}} y^i_{t} \\
    c^i_{2,t+1} &= \frac{\alpha p_{t+1}}{1+\alpha p_{t+1}}(1-\tau_{t+1})\hat{R}_{t+1}y^i_{t} \\
    s^i_t &= \frac{\alpha p_{t+1}}{1+\alpha p_{t+1}} y^i_t
\end{align*}
where \(e\) corresponds to employed young agents and \(u\) to the unemployed ones.
Since the utility function is logarithmic, this is a standard result where the saving is a constant proportion of the income.
Each household faces an idiosyncratic unemployment risk with probability \(u_t \in \left[0,1\right)\). The income of an employed young agent is \(y^e_t = (1-\tau_t)w_t\), while an unemployed young agent earns \(y^u_t = b_t\), where \(w_t\) is the wage and \(b_t\) the unemployment benefits per capita. The aggregate saving in the economy is \(S_t = (1-u_t) N_t^y s^e_t + u_t N_t^y s^u_t\). Thus,
\begin{equation}
  S_t = \frac{\alpha p_{t+1}}{1+\alpha p_{t+1}}\left[ (1-u_t)(1-\tau_t)w_t + u_t b_t \right] N_t^y \label{eq:agg-saving}
\end{equation}

At the beginning of each period, a voting takes place to determine the public policy. Agents maximize their indirect utility function to determine the tax rate \(\tau_t\), the unemployment benefits per capita \(b_t\) and the government health spending per capita \(h_t\).
The indirect utility of a young agent at time \(t\) is:
\begin{equation}
    U_t^{y,i} = \ln\left(\frac{1}{1+\alpha p_{t+1}}y_t^i\right)+ \alpha p_{t+1} U_{t+1}^{o,i} ~~ \forall i = \lbrace e,u \rbrace \label{eq:utility-young}
\end{equation}
While the indirect utility of an old agent at time \(t\) depends on its income in \(t-1\). Hence,
\begin{equation}
    U_t^{o,i} = \ln\left(\frac{\alpha p_t}{1+\alpha p_t}(1-\tau_t)y_{t-1}^i\hat{R}_t\right) + \beta \ln h_t ~~ \forall i = \lbrace e,u \rbrace \label{eq:utility-old}
\end{equation}
Using equation @ref\{eq:utility-young), I compute the gap between employed and unemployed people in utility terms and obtain:
\begin{equation}
    U_t^{y,e} - U_t^{y,u} = (1+\alpha p_{t+1})\ln\left[\frac{(1-\tau_t)w_t}{b_t}\right] \label{eq:utility-young-gap}
\end{equation}
Young individuals are not aware of their employment status before to vote. Hence, they have to maximize their indirect utility with expectations on their income. The expected income of each young individual is a weighted average of both incomes (labor income and unemployment benefits). Thus, \(\mathbb{E}(y_t) = (1-u_t)(1-\tau_t)w_t + u_tb_t\), where \(\mathbb{E}\) is the expectation operator. Computing the expected utility of a young household at time \(t\), I obtain:
\begin{equation}
    \mathbb{E}({U}_t^y) = \ln\left(\frac{\mathbb{E}\left(y_t\right)}{1+\alpha p_{t+1}}\right) + \alpha p_{t+1}\left\lbrace \ln\left(\frac{\alpha p_{t+1}}{1+\alpha p_{t+1}}(1-\tau_{t+1})\mathbb{E}(y_t)\hat{R}_{t+1}\right) + \beta \ln h_{t+1} \right\rbrace \label{eq:expected-utility-young}
\end{equation}

\hypertarget{production}{%
\subsection{Production}\label{production}}

Firms are represented by a representative firm that uses a standard CES production function given by:
\begin{equation}
Y_t = A\left[ \phi K_t^{\frac{\sigma - 1}{\sigma}} + (1-\phi) L_t^{\frac{\sigma - 1}{\sigma}}\right]^{\frac{\sigma}{\sigma-1}} \label{eq:prod}
\end{equation}
where \(K_t\) is the capital stock, \(L_t\) the labor, \(\sigma\) the elasticity of substitution between capital and labor, \(\phi\) the factor share parameter allowing the relative importance of inputs in production to vary and \(A\) a constant scale parameter. I do not consider any form of technical change, whether neutral or biased. Rewriting the production function in units of labor,
\begin{equation}
    \frac{Y_t}{L_t} = A\left(\phi k_t^{\frac{\sigma-1}{\sigma}} + 1-\phi\right)^{\frac{\sigma}{\sigma-1}} \label{eq:prod/L}
\end{equation}
where \(k_t\equiv K_t/L_t\) is the capital-per-worker (i.e.~capital intensity). Since the economy is closed and capital fully depreciates between two periods, the capital in the economy is determined by the saving of the previous period, i.e.~\(K_t = S_{t-1}\). The labor-demand equation obtained from the profit maximization of the representative firm is:
\begin{equation}
    w_t = (1-\phi)A\left(\phi k_t^{\frac{\sigma-1}{\sigma}}+1-\phi\right)^{\frac{1}{\sigma-1}} \label{eq:labor-demand}
\end{equation}
The labor demand elasticity is defined as \(\mathcal{E}^{L,w}_t=\frac{\partial L_t}{\partial w_t}\frac{w_t}{L_t}\). Using the equation \eqref{eq:labor-demand},
\begin{equation}
    \mathcal{E}^{L,w}_t = -\sigma\left(1+\frac{1-\phi}{\phi}k_t^{\frac{1-\sigma}{\sigma}}\right) \label{eq:labor-elasticity}
\end{equation}
Using equations \eqref{eq:prod/L} and \eqref{eq:labor-demand}, I compute the labor share \(\theta_t = \frac{w_tL_t}{Y_t}\) which is:
\begin{equation}
    \theta_t = \left(1+\frac{\phi}{1-\phi}k_t^{\frac{\sigma-1}{\sigma}}\right)^{-1} \label{eq:theta}
\end{equation}
This equation holds if and only if the representative firm is on its labor demand curve. Notice that when the capital-labor elasticity of substitution equals unity, then \(\theta_t=1-\phi\). In this case, the production function is Cobb-Douglas and the labor income share is constant in \(k_t\). When \(\sigma \to 0\), the production function is Leontief. When \(\sigma \to +\infty\), the production function is linear.
Hence, I define the elasticity of substitution between capital and labor such as \(\sigma\in\mathbb{R}_+^\star\setminus\lbrace1\rbrace\).
As long as the representative firm is not constrained in its ability to hire and fire workers, it means that the firm is on its labor demand curve and thereby the labor share only depends on \(k_t\).\footnote{Considering a small open economy (SOE), the capital-labor ratio becomes constant. \citet{Schmidt2013} show that, in such a case, the labor share dynamics only reflects variations in net foreign assets of the economy.}
With the equation \eqref{eq:theta}, I compute the labor-to-capital income ratio \(\Theta_t = \frac{\theta_t}{1-\theta_t}\) which is:
\begin{equation}
    \Theta_t = \frac{1-\phi}{\phi}k_t^{\frac{1-\sigma}{\sigma}} \label{eq:Theta}
\end{equation}

The comparative statics are straightforward,
\begin{equation*}
    \left\lbrace ~~
    \frac{\partial w_t}{\partial k_t} > 0,~~
    \frac{\partial (Y_t/L_t)}{\partial k_t} > 0,~~
    \frac{\partial \theta_t}{\partial k_t} \lessgtr 0 ~~
    \right\rbrace, ~~ \sigma \gtrless 1
\end{equation*}
A higher capital-labor ratio increases the wage resulting from the labor demand equation and the production-per-worker. However, the impact on the labor share depends on the elasticity of substitution between both input factors. When capital and labor are gross substitute (i.e.~\(\sigma > 1\)), a higher capital-labor ratio decreases the labor share. While the relationship is positive when both input factors are gross complement (i.e.~\(\sigma < 1\)). Since the labor share can be defined as the ratio between wage and production-per-worker, it means that with gross substitute input factors, a rise of the capital-per-worker increases more the production-per-worker relatively to the wage rate. Vice versa when \(\sigma <1\). Thus,
\begin{equation*}
    \left\lbrace ~~
    \frac{\partial w_t}{\partial k_t} ~\lessgtr~ \frac{\partial (Y_t/L_t)}{\partial k_t} ~~
    \right\rbrace, ~~ \sigma \gtrless 1
\end{equation*}
In order to have a negative relationship between the capital-to-labor ratio and the labor share without the presence of biased technical change, both input factors must be gross substitute (i.e.~\(\sigma >1\)).

\hypertarget{public-policy-preferences}{%
\subsection{Public policy preferences}\label{public-policy-preferences}}

The government taxes the labor income of young households and the savings return of old households in period \(t\) at rate \(\tau_t\). Government revenue is spent in unemployment benefits and health expenditure, so that the government budget constraint is given by \(\tau_t\left( w_t(1-u_t)N^y_t + R_t S_{t-1} \right) = b_t u_t N^y_t + h_t N^o_t\). Capital fully depreciates between two periods, thus \(R_t = r_t\) and \(K_t = S_{t-1}\), where \(r_t\) is the rental price of capital, and hence the government budget constraint can be written as \(\tau_t Y_t = b_t u_t N^y_t + h_t N^o_t\).

Young and old agents vote at the beginning of each period. The youth desire more unemployment benefits since they cover the risk to be unemployed. While the elderly desire more health spending because they derive utility from it. \emph{Everything else equal}, both desire less taxes as it reduces their disposable income. Therefore, young and old agents have different objectives on public policy preferences. I model the inter-generational conflict over public budget allocation with this trade-off but it could be extended to other public policy instruments. The central point is to oppose young and old individuals with different returns in utility terms of policy instruments.

\citet{Sorensen2013} analyzes cross-section survey data for 22 countries and shows that agents change their public spending preferences over their life-cycle. Thus, he provides evidence for an age-related selfishness in public spending preferences. In line with these results, I consider a probabilistic voting setup in contrast to the median voter setup.\footnote{The median voter setup would create two extreme regimes with one of them being a gerontocracy. It would also generate large changes in public policy if the median-voter switches from young to old or vice versa. Under probabilistic voting, the equilibrium policy platform is a continuous function of the old-age dependency ratio. This setup smooths public policy changes in line with the literature of recent politico-economic models.}

With probabilistic voting, all agents vote for a policy platform \(g_t = (\tau_t, b_t, h_t)\) represented by opportunistic candidates (or parties). Candidates try to maximize their probability of winning the election. They differ in their popularity and there is an idiosyncratic bias among voters for one candidate or the other. Candidates know about these biases. At equilibrium, all candidates choose the same policy platform \(g_t^\star\) that maximizes the political objective function \(W_t(g_t)\).\footnote{See \citet{Lindbeck1987} for more details on the probabilistic-voting setup.}

This function depends on the population share of voter group and their respective sensitivity to policy changes \(\omega^j\) with \(j \in \left(y,o\right)\).\footnote{\(\omega^j\) denotes the density parameter of the uniform distribution function that characterizes the ideology of the \(j\) group. The greater \(\omega^j\), the more spread are the ideologies withing the \(j\) group. Hence, opportunistic candidates prefer targeting less ideological groups, i.e.~large \(\omega^j\), because they are easier to convince.} There are three groups of voters: young households; and old households who are divided in two subgroups according to their employment situation when young. I assume that all the elderly have the same sensitivity \(\omega^o = \omega^{o,u} = \omega^{o,e}\). Thus, the equilibrium public policy \(g_t^\star\) maximizes the following function:
\begin{equation*}
    W_t(g_t) = \frac{N_t^y}{N_t} \omega^y \mathbb{E}\left[U_t^y(g_t)\right] + \frac{N_t^o}{N_t} \omega^o \Big\{ u_{t-1} U_t^{o,u}(g_t) + (1-u_{t-1}) U_t^{o,e}(g_t) \Big\}
\end{equation*}
Subject to the indirect utilities implied by the equations \eqref{eq:utility-old} and \eqref{eq:expected-utility-young}; and to the government budget constraint.
I assume that individuals only care about direct effects of public policy on their utility. They do not consider the indirect effects operating through unemployment, wages and the accumulation of capital.\footnote{An interpretation of this assumption is that agents are not able to predict what will be the response of the labor market to changes in public policy. Otherwise stated, the investment of effort to be perfectly informed and able to calculate the indirect effects of different public policies is too costly for an individual (or at least a representative share of the electorate). Thus, rationality is limited to the direct effects on the utility function. This is related to political science literature and the concept of \emph{synoptic rationality}. See \citet{Meier1980} for more details.} Let \(\tilde{U}^i_t\) be the part of the utility which is directly affected by the public policy platform. From \eqref{eq:utility-old}, it is straightforward that \(\tilde{U}_t^o = \tilde{U}_t^{o,u} = \tilde{U}_t^{o,e}\). Therefore, the political objective function can be rewritten as:
\begin{equation*}
    W_t(g_t) = \frac{N_t^o}{N_t} \omega^o \tilde{U}_t^o(g_t) + \frac{N_t^y}{N_t} \omega^y \tilde{U}_t^y(g_t) + \text{other terms}
\end{equation*}
where \(\text{other terms}\) encompasses all the terms that are not directly affected by the public policy. Let \(\omega\) be the \emph{relative ideological spread-out} of the elderly with respect to the youth. This relative ideological spread-out is characterized by the ratio of the sensitivities of voting behavior to policy changes for each group. Thus, \(\omega \equiv \omega^o/\omega^y\). I assume that this spread-out is constant over time.\footnote{Two interpretation for this assumption are plausible: either both relative ideological spread-outs are time invariant; or they vary in same proportions. An interesting point would be to endogenize these spread-outs or to make them cohort-specific. Nevertheless, this goes beyond the scope of this paper.} Using equations \eqref{eq:utility-old} and \eqref{eq:expected-utility-young}, I rewrite the maximization program that characterize the public policy equilibrium as:
\begin{align*}
    \max_{\tau_t, b_t, h_t} W_t(\tau_t, b_t, h_t) &= \ln(1-\tau_t) +\beta \ln(h_t) + \eta_t \ln\left[(1-u_t)(1-\tau_t)w_t + u_t b_t\right] + \text{other terms} \\
    \text{s.t.} ~~ &\tau_t Y_t = b_t u_t N^y_t + h_t N^o_t
\end{align*}
where
\begin{equation}
    \eta_t = \frac{n_t}{p_t}\frac{1+\alpha p_{t+1}}{\omega} \label{eq:eta}
\end{equation}
is political weight of the youth. This variable is the channel through which the age structure affects the public policy. It depends negatively on the old-age dependency ratio \(p_t/n_t\), the older the population the lower the political weight of the youth within the policy determination. It also depends negatively on the relative ideological spread-out \(\omega\). The less ideological is the youth, the higher will be its political weight. If young people are less ideologically tenacious, then it is easier for the opportunistic candidates to get their votes with an appropriated public policy. As a consequence, candidates pay more attention to them.\footnote{Otherwise stated, the less spread-out is the ideology distribution within a group, the more numerous are the voters that swing after changes in public policy platform.} \(\eta_t\) is increasing in \(\alpha p_{t+1}\), corresponding to the fact that young voters are more likely to swing in favor of a pro-labor-income policy platform. The longer they expect to live, the more they will have to save in order to smooth their consumption, therefore, they require a relatively greater first-period income.
Focusing on the interior solution, the first order conditions lead to the following public policy preferences:
\begin{align}
    \frac{b_t}{(1-\tau_t)w_t} &= \frac{1-u_t}{u_t} \left(\eta_t\frac{1-\theta_t}{\theta_t}- 1\right),
    \label{eq:inverse-replacement-rate}\\
    \tau_t &= 1 - \left[\left(1-\theta_t\right)\left(1+\beta+\eta_t\right)\right]^{-1},
    \label{eq:tax-rate} \\
    h_t N^o_t &= \frac{\beta}{1+\beta+\eta_t}Y_t,
    \label{eq:health-expenditure}
    \end{align}
where the first equation is the unemployment replacement rate, the second the tax rate and the third health expenditure. The comparative statics are straightforward,
\begin{equation*}
    \left\lbrace \frac{\partial \frac{b_t}{(1-\tau_t)w_t}}{\partial \eta_t} > 0, ~ \frac{\partial \tau_t}{\partial \eta_t} > 0, ~\frac{\partial h_t}{\partial \eta_t} < 0\right\rbrace.
\end{equation*}
Young generations desire more redistribution and a higher unemployment replacement rate because they face an unemployment risk. Such a public policy allows them to increase their expected income. However, they vote to reduce the government health spending because they do not derive utility from it yet.\footnote{I do not consider any form of explicit altruism. However, the parameter \(\beta\) which is the preference for government health spending captures a form of altruism from young to their elders. The greater the parameter, the more individuals care about government health spending once old. Finally, a form of explicit altruism from young to old generations would smooth the results and soften the age-related conflict.}

The aggregate income of young households is \(Y_t^y = \left[(1-u_t)(1-\tau_t)w_t+b_tu_t\right]N_t^y\). Using equation \eqref{eq:inverse-replacement-rate} and \eqref{eq:tax-rate}, it can be written as a share of the total income \(Y_t\) such that
\begin{equation*}
    \frac{Y_t^y}{Y_t} = \frac{\eta_t}{1+\beta+\eta_t}.
\end{equation*}
\%Young households decide to save a share of their income in order to smooth their consumption for the second period, this share depends on their life expectancy. The remaining income is consumed. From section \ref{households}, these shares are:
Note that total income is split between the incomes of both groups and health spending. Thus, \(Y_t = Y_t^y + Y_t^o + h_tN_t^o\). Hence, using equation \eqref{eq:health-expenditure}, the elderly income share is given by
\begin{equation*}
    \frac{Y_t^o}{Y_t} = \frac{1}{1+\beta+\eta_t}.
\end{equation*}
For a given level of total income \(Y_t\), the comparative statics are unambiguous. When the youth's political weight raises, young individuals increase their income share with more redistribution, i.e.~\(\partial(Y_t^y/Y_t)/\partial\eta_t>0\). Conversely, the elderly income share decreases and so does the government health spending, i.e.~\(\partial (Y_t^o/Y_t)/\partial\eta_t<0\) and \(\partial(h_tN_t^o/Y_t)/\partial\eta_t<0\). A higher \(eta_t\) can be due to two changes: either a decrease of the old-age dependency ratio (\(p_t/n_t \searrow\)) or an increase of the survival rate of the current young generation (\(p_{t+1} \nearrow\)).
Furthermore, it is possible to express the after-tax income ratio between young and old households as:
\begin{equation}
    \frac{Y_t^y}{Y_t^o} = \eta_t \label{eq:after-tax-income-ratio}
\end{equation}
As expected, the greater is the political weight of the young, the greater redistribution and the gap between both incomes are.

\hypertarget{wage-bargaining}{%
\subsection{Wage bargaining}\label{wage-bargaining}}

These public policy instruments interact with the outcome of the wage bargaining to determine the equilibrium of the economy.
There is a single union that represents the workers. In order to model wage bargaining, I consider a ``Right-to-manage'' model \emph{à la} \citet{Nickell1983}. The union bargains only over wages with the employer retaining the prerogative to hire and fire.\footnote{Another possibility would have been to consider an ``Efficient contract'' model \emph{à la} \citet{McDonald1981} where the union bargains over wages and employment. However, this specification does not fit well the data as \citet{Bentolila2003} showed. Moreover, it would add a lot of complexity to the model without a substantial gain in the analysis.} Consequently, the firm is always on its labor demand curve and equation \eqref{eq:labor-demand} holds. The union wants to maximize the workers' utility compared to the unemployed, i.e.~\(L_t\left(U^{y,e}_t - U^{y,u}_t\right)\). The representative firm maximizes its outside option which is \(Y_t-w_tL_t\) corresponding to \(r_t K_t\). Thus, the outcome of the bargaining process is determined by the maximization program following
\begin{align*}
  \max_{w_t>0} ~~ &\lbrace \left(L_t[U^{y,e}_t - U^{y,u}_t]\right)^\gamma \left(Y_t-w_tL_t\right)^{1-\gamma}\rbrace\\
    \text{s.t.} ~~ &U_t^{y,e} - U_t^{y,u} = (1+\alpha p_{t+1})\ln\left[\frac{(1-\tau_t)w_t}{b_t}\right],
\end{align*}
where \(\gamma\in(0,1)\) is the relative bargaining power of the union. The first-order condition can be expressed as
\begin{equation*}
    \frac{\gamma}{1-\gamma}\left\lbrace\mathcal{E}^{L,w}_t\ln\left[\frac{(1-\tau_t)w_t}{b_t}\right]+1\right\rbrace = \ln\left[\frac{(1-\tau_t)w_t}{b_t}\right] \frac{w_tL_t}{Y_t-w_tL_t}, \label{eq:foc-wage-bargaining}
\end{equation*}
where \(\mathcal{E}^{L,w}_t\) is the labor demand elasticity. Using equations \eqref{eq:labor-elasticity} and \eqref{eq:theta}, I can express the optimal capital-per-worker as a function of the unemployment replacement rate:
\begin{equation}
    k_t(X_t) = \left[\frac{1-\phi}{\phi}\frac{1-\gamma(1-\sigma)}{\gamma}\frac{X_t}{1-\sigma X_t}\right]^{\frac{\sigma}{\sigma-1}} \label{eq:k-x}
\end{equation}

where \(X_t=\ln\left[\frac{(1-\tau_t)w_t}{b_t}\right]\) is the value-added of being employed (in utility terms) which only depends on the unemployment replacement rate. Since capital-per-worker has to be positive, it implies that \(1-\sigma X_t > 0\). The maximum capital-labor elasticity of substitution ensuring that this condition is met can be defined as the function \(\bar{\sigma}(x_t) = -\log^{-1}(x_t)\), where \(x_t\) is the unemployment replacement rate. Table \ref{tab:xsigma} presents the lowest unemployment replacement rate per country over the period 1970-2010.

For France and the United-States, itcorrespond, respectively, to 0.592 and 0.567. Hence, the condition is met for all \(\sigma\) between zero and 1.907 for France or 0.567 for the United-States. In what follows, I assume that \(1>\sigma X_t\) is always satisfied. The comparative statics with respect to \(X_t\) are as follows

\begin{equation*}
    \left\lbrace \frac{\partial k_t}{\partial X_t} \gtrless 0 \Rightarrow 
    \left\lbrace \frac{\partial w_t}{\partial X_t} \gtrless 0,~~
    \frac{\partial (Y_t/L_t)}{\partial X_t} \gtrless 0,~~ \frac{\partial w_t}{\partial X_t} <
    \frac{\partial (Y_t/L_t)}{\partial X_t} \right\rbrace \Rightarrow 
    \frac{\partial \theta_t}{\partial X_t} < 0
    \right\rbrace, ~~ \sigma \gtrless 1
\end{equation*}

When the unemployment replacement rate \(\frac{b_t}{(1-\tau_t)w_t}\) increases, the value-added of having a job \(X_t\) falls. Hence, the labor share \(\theta_t\) increases. The intuition is that when the unemployment replacement rate increases it allows the union to bargain a higher wage and so to grab a relatively larger share of income. This mechanism holds whatever the value of the capital-labor elasticity of substitution \(\sigma\).
However, intermediate partial derivatives are just transitional and consider only the partial effect of a change in the unemployment replacement rate.

\hypertarget{equilibrium}{%
\subsection{Equilibrium}\label{equilibrium}}

Voting and wage bargaining take place simultaneously and there is no-coordination between the two. As a consequence, both processes take the outcome of the other as given. The interaction determines the equilibrium of the economy. Expressing equations \eqref{eq:inverse-replacement-rate} and \eqref{eq:k-x} as function of the capital-labor ratio. We have that equilibrium is given by the solution to the following system:
\begin{align}
  X_t &= \ln\left( \frac{ \frac{N_t^y}{K_t} k_t - 1 } { \frac{\phi}{1-\phi}     
  k_t^{\frac{\sigma-1}{\sigma}} \eta_t - 1 }\right), \label{eq:Xg} \\ 
    X_t &= \left( \sigma + \frac{1-\phi}{\phi} \frac{1-\gamma(1-\sigma)}{\gamma} k_t^{\frac{1-\sigma}{\sigma}} \right)^{-1}, \label{eq:Xh}
    \end{align}
which yields the equilibrium capital-labor ratio and employment value-added. Note that at time \(t\), the aggregate capital stock \(K_t\) is predetermined by the saving decisions at \(t-1\), so that \(k_t\) is given by \(L_t\). The Cobb-Douglas case, i.e.~\(\sigma = 1\), can be solved analytically and leads to the following equilibrium:
\begin{align*}
    X_t &= \frac{\gamma}{1-\phi(1-\gamma)} \\
    k_t &= \left[1 + e^{X_t}\left(\frac{\phi}{1-\phi}\eta_t-1\right)\right]\frac{K_t}{N_t^y}
\end{align*}
The value-added to have a job is constant, while the capital-per-worker is determined by demographic variables and is proportional to the capital-per-young individual. However, this case is not useful to examine the labor share's dynamics as the labor share is constant with a Cobb-Douglas technology (\(\theta_t = 1-\phi\)). In appendix \ref{app-A}, I show that the equilibrium is unique for any other value of sigma. The equilibrium is characterized by 13 equations,
\begin{align}
    \eta_t &= \frac{n_t}{p_t}\frac{1+\alpha p_{t+1}}{\omega}, \\
    X_t &= \ln\left( \frac{ \frac{N_t^y}{K_t} k_t - 1 } { \frac{\phi}{1-\phi} k_t^{\frac{\sigma-1}{\sigma}} \eta_t - 1 }\right), \label{eq:g} \\
    X_t &= \left( \sigma + \frac{1-\phi}{\phi} \frac{1-\gamma(1-\sigma)}{\gamma} k_t^{\frac{1-\sigma}{\sigma}} \right)^{-1}, \label{eq:h}\\
    L_t &= \frac{K_t}{k_t},\\
    w_t &= A(1-\phi)\left( \phi k_t^\frac{\sigma-1}{\sigma} + 1-\phi \right)^\frac{1}{\sigma-1},\\
    Y_t &= A \left[ \phi K_t^\frac{\sigma-1}{\sigma} + (1-\phi) L_t^\frac{\sigma-1}{\sigma} \right]^\frac{\sigma}{\sigma-1},\\
    u_t &= 1 - \frac{L_t}{N_t^y},\\
    \theta_t &= \left(1 + \frac{\phi}{1-\phi} k_t^\frac{\sigma-1}{\sigma} \right)^{-1},\\
    \tau_t &= 1 - \left[ (1-\theta_t)(1+\beta+\eta_t) \right]^{-1},\\
    b_t &= (1-\tau_t) w_t e^{-X_t},\\
    h_t &= \frac{\tau_t Y_t - b_t u_t N_t^y}{N_t^o},\\
    S_t &= \frac{\alpha p_{t+1}}{1 + \alpha p_{t+1}} \left[ (1-\tau_t)w_t(1-u_t) + b_tu_t \right] N_t^y,\\
    K_{t+1} &= S_t.
\end{align}
Let define, respectively, equations \eqref{eq:g} and \eqref{eq:h} with the functions \(g(L_t, K_t, \eta_t, N_t^y; \phi, \sigma)\) and \(h(L_t, K_t; \sigma, \phi, \gamma)\), such that:
\begin{align*}
    X_t &= g(L_t, K_t, \eta_t, N_t^y; \phi, \sigma) \\
    X_t &= h(L_t, K_t; \sigma, \phi, \gamma)
\end{align*}
Differentiating this system, I find that
\begin{align*}
    dX_t &= g_L dL_t + g_K dK_t + g_\eta d\eta_t + g_{N^y} dN_t^y, \\
    dX_t &= h_L dL_t + h_K dK_t,
\end{align*}
where \(f_x\) is the partial derivative of \(f\) with respect to \(x\). Solving the system, I have
\begin{equation*}
    dL_t = \frac{1}{h_L-g_L}\left[(g_K-h_K) dK_t + g_\eta d\eta_t + g_{N^y} dN_t^y \right]
\end{equation*}
The variables \(\eta_t\) and \(N_t^y\) are given by the demographic dynamics while the capital stock \(K_t\) is given by savings of the previous period. Thus, the variable that determines the equilibrium is the level of employment \(L_t\). Partial derivatives are derived in \ref{app-B}.
\(g_\eta\) is negative because the greater is the youth's political power, the greater is the unemployment benefit and the smaller is the value-added to have a job. \(g_{N^y}\) is positive because the more numerous the young are, the more these unemployment benefits are divided among them and so the smaller is the value-added to have a job. The sign of \(g_K-h_K\) depends on the value of \(\sigma\) with \(g_K-h_K \lessgtr 0, ~ \forall \sigma \gtrless 1\). This is directly related to the fact that both factors are either gross substitutes or gross complements. When labor and capital are gross substitutes, more capital requires less labor for a given of level of output, while when they are complements, the representative firm has to jointly increase labor and capital stock in order to maintain the same production level. Lastly, the sign of \(h_L-g_L\) is ambiguous.\footnote{When \(\sigma < 1\), then \(g_L\) and \(h_L\) are both positive, thus, \(g_L-h_L\) is ambiguous. When \(\sigma > 1\), \(h_L\) is unambiguously negative. The sign of \(g_L\) cannot be determined without additional assumptions. If \(\eta_t/\Theta_t > \sigma\), then \(g_L\) is negative. Otherwise, \(g_L\) is negative if the unemployment rate is lower than a certain threshold, i.e \(u_t < \bar{u}_t\) where \(\bar{u}_t = \left(2 - \frac{\eta_t}{\Theta_t\sigma}\right)^{-1}\). Thus, when the unemployment rate is high enough such that \(u_t > \bar{u_t}\), \(g_L\) is unambiguously positive and so is \(g_L-h_L\). This is the only case where it is possible to determine unambiguously the impact of variables on \(L_t\). In such a case, \(\frac{dL_t}{dK_t}\Bigr|{\substack{d\eta_t = 0\\dN_t^y = 0}} < 0\), \(\frac{dL_t}{dN^y_t}\Bigr|{\substack{dK_t = 0\\d\eta_t = 0}} > 0\) and \(\frac{dL_t}{d\eta_t}\Bigr|{\substack{dK_t = 0\\dN_t^y = 0}} < 0\). Therefore, except in this special case, \(g_L-h_L\) is ambiguous.} Due to this ambiguity, I perform a quantitative analysis in section \ref{quantitative}.

\hypertarget{quantitative}{%
\section{Quantitative analysis}\label{quantitative}}

This section provides a quantitative analysis of the model, with three main objectives: to reproduce the labor share dynamics observed over the period 1970 to 2010, to produce model predictions and to understand the transmission channels of demographic effects on the labor share. Based on analytical results, I compute quantitative predictions for France and the United-States.

\hypertarget{calibration}{%
\subsection{Calibration}\label{calibration}}

One period in the model corresponds to 40 years in the data. Following the methodology of \citet{Gonzalez-Eiras2012} to simulate an OLG model, I compute four sequences of model predictions with a period length of 40 years each. Periods of the first sequence corresponds to 1970, 2010, 2050, \ldots; for the second sequence to 1980, 2020, 2060, \ldots; for the third sequence to 1990, 2030, 2070, \ldots; for the fourth sequence to 2000, 2040, 2080, \ldots. When reporting time series predictions, I list the four sequences in a single time series.
With a period length of 40 years, agents are considered as young between 20 and 60 years of age and as elderly thereafter.\footnote{An implicit assumption of the model is that the retirement age is constant (this assumption is discussed in section \ref{discussion}. The average French effective retirement age was 67.8 in 1970 and has declined to 59.3 in 2010. In the US it has gone from 68.4 to 65.6 over the same period (data from the \href{https://www.oecd.org/els/emp/average-effective-age-of-retirement.htm}{OECD Database, Ageing and Employment Policies - Statistics on average effective age of retirement}). I suppose, as an approximation, that agents retire at 60 years-old to match the period lengths of the calibration. Such an assumption should not affect the voting outcome because almost-retired agents may anticipate their future situation once they vote. However, there could be implications in terms of labor supply. Nonetheless, a 5-year approximation remains marginal compared to the 40 years between the two periods. } I compute the old-age dependency ratio from the data as the number of old people divided by the number of young people (i.e.~\(p_t/n_t \equiv N_t^o/N_t^y\)). Then, the population growth rate at time \(t\) is computed using the ratio between the number of young households in period \(t\) relative to the number of young households in the previous period of the sequence (i.e.~\(n_t = N_t^y/N_{t-1}^y\)). Finally, the survival rate at time \(t\) is the product of the old-age-dependency ratio and the population growth.\footnote{Demographic data from 1950 are taken from the \href{https://population.un.org/wpp/}{United Nations World Population Prospects 2017}. Demographic data before 1950 are from \url{http://www.populstat.info}. Demographic data between 2010 and 2100 are the ``medium variant'' estimates from the United Nations. Both rates \(n_t\) and \(p_t\) converges to unity in the very long run (after the 5th period of the 4th sequence, hence 2160). However, I limit my analysis to 3 periods (hence 2080) due to high uncertainty above 100 years.} Figure \ref{fig:demo} plots demographic variables for both countries.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/demo-1} 

}

\caption{Demographic variables time trends}\label{fig:demo}
\end{figure}

\begin{table}[t]

\caption{\label{tab:param}Parameters}
\centering
\begin{threeparttable}
\begin{tabular}{llrr}
\toprule
 & Parameter & France & United States\\
\midrule
$\phi$ & Capital share in 1970 & 0.270 & 0.325\\
$\gamma$ & Relative bargaining power of the union & 0.500 & 0.500\\
$\alpha$ & Discount rate & 0.669 & 0.669\\
$\sigma$ & Capital-labor elasticity of substitution & 1.321 & 1.234\\
$\omega$ & Relative ideological spread-out & 0.983 & 1.533\\
$\beta$ & Preference for government health expenditure & 0.739 & 0.138\\
A & Scale parameter of the production function & 23.891 & 22.840\\
\bottomrule
\end{tabular}
\begin{tablenotes}[para]
\item \textit{Note: } 
\item Single-equation estimation of s from the two first-order conditions of the profit maximization with normalized CES production function. s estimates are significant at p < 0.1 for France and p < 0.05 for the United States. Details in appendix \ref{app-C}.
\end{tablenotes}
\end{threeparttable}
\end{table}

Economic variables data (\(K_t\), \(emp_t\), \(Y_t\), \(\theta_t\)) are taken from the \href{https://www.rug.nl/ggdc/productivity/pwt/}{Penn World Table 9.1}.\footnote{\(K\) is the capital stock at constant 2011 national prices, \(emp\) the number of persons engaged, \(Y\) the real GDP at constant 2011 national prices and \(\theta\) the share of labor compensation in GDP. \(K\) and \(Y\) are adjusted with the average annual hours worked by persons engaged. For further details the reader is referred to \citet{Feenstra2015}.} When considering data on the labor share, I use the first adjustment method of \citet{Feenstra2015}.\footnote{\citet{Gollin2002} argues that it is necessary to take into account self-employed income. In the model, workers are only young individuals and provide only labor supply. Therefore, I assume that self-employed individuals earn an income that is characterized as a compensation.} I use government revenue as a share of GDP from the \href{https://data.oecd.org/tax/tax-revenue.htm}{OECD database} as proxy for the tax rate \(\tau_t\).
In the model, labor supply is inelastic and there is no distinction between unemployed and inactive young individuals. Unemployed agents in terms of the model specification correspond to all agents that do not work. However, in high-income countries, such as France and United States, inactive individuals also benefits from redistribution. Therefore, I treat inactive individuals as unemployed and the redistribution is captured through unemployment benefits \(b_t\) in the model.
I compute the unemployment rate such that \(u_t = 1 - emp_t/N^{15-64}_t\), where \(N_t^{15-64}\) is the working age population.\footnote{I consider the whole working age population instead of the young population in order to compute the unemployment rate. Due to demographic specification of the model, young agents correspond to those between 20 and 60 years old. The number of persons engaged (\(emp\)) per age groups are not available in \href{https://www.rug.nl/ggdc/productivity/pwt/}{PWT 9.1}. Therefore, taking only \(N^y_t\) as denominator would bias downward the unemployment rate. Results are robust to different specifications of the unemployment rate.}
Then, I compute labor such that \(L_t=(1-u_t)N_t^y\). I normalize \(K_t\) and \(L_t\) to their 1970 values. As a consequence, the capital-to-labor ratio \(k_t\) is also normalized and is equal to 1 in 1970. Then, \(N_t^y\) and \(N_t^o\) are normalized such that \(u_t\) matches the data in 1970.

Once all stock variables are normalized, I calibrate the seven remaining parameters \(\lbrace \phi, \sigma, \gamma, \alpha, \omega, \beta, A \rbrace\). Table \ref{tab:param} summarizes parameters for both countries.
\% Parameters table
The first parameter \(\phi\) corresponds to the capital share in 1970. Because the capital-labor ratio is normalized (i.e.~\(k_{1970} = 1\)), the labor share \(\theta\) in 1970 is equal to \(1-\phi\), allowing me to determine \(\phi\). I set the relative bargaining power of the union \(\gamma\) to 0.5. Hence, I assume that neither the representative union nor the representative firm have any other advantage in the bargaining apart from their respective outside options. I also set the discount rate at 0.669 in line with the literature.

The main parameter of the model is the elasticity of substitution between capital and labor \(\sigma\). I estimate it using a combination of the first order conditions of the profit maximization. Details of the estimation in \href{app-C}{appendix C}. I obtain 1.279 and 1.234, respectively, for France and the United States. According to the estimation, both input factors are gross substitute. These estimates are in line with \citet{Karabarbounis2014} who use cross-sectional data on 50 countries over the period 1975-2012 to find an elasticity greater than 1 and on average around 1.28 in their baseline estimates.

Then, I have three remaining parameters that are deduced. The relative ideological spread-out \(\omega\) is set such that the model prediction matches the capital-to-labor ratio \(k\) in 1970. The preference for government health expenditure \(\beta\) is set to match the tax rate \(\tau\) in 1970. Lastly, the scale parameter of the production function \(A\) is set with grid-search to match the average labor share between 2008 and 2012 for each country.

Due to initial labor share values, the parameter distribution \(\phi\) which correspond to the capital share in 1970 is larger in the United States than in France. Moreover, the relative per-capita political influence of old households \(\omega\) is also greater. This deduced parameter suggests that young generations have less political weight in the United States compared to France. Notice that \(\omega\) is lower than one for France. It implies that French youth voting behavior is more sensitive to policy changes compared to elderly. French households have a much greater preference for government health expenditure \(\beta\). Finally, the scale parameter \(A\) is ranged between 20 and 30 for both countries.

\hypertarget{pred7010}{%
\subsection{Model predictions over the period 1970-2010}\label{pred7010}}

Figure \ref{fig:baseline7010} displays the labor share over the period 1970-2010, depicting both model predictions and the data.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/baseline7010-1} 

}

\caption{Model prediction of the labor share (1970-2010)}\label{fig:baseline7010}
\end{figure}

The model reproduces the trend in the data for both countries.
For the United States, the model tends to overestimate the labor share in 1980 and 1990 and underestimate it in 2000.
However, model predictions capture the global trend of the labor share over the period.
For France, the dashed curve is the model prediction with a capital-labor elasticity of substitution of 1 in 1970-1980 and about 1.321 thereafter. The scale parameter \(A\) is also changed to 23.891 for France. The initial calibration of the model, as in section \ref{calibration}, is not able to reproduce the large decline in the labor share between 1980 and 1990. This may be explained by factors not considered in the model.
I model the workers outside option within the wage bargaining using only unemployment benefits and the tax rate but other labor market institutions may have played a role in firms' employment policies during this period. For example, in my framework, there is no firing cost. \citet{Bentolila1990} argue that firing costs have an effect on firms' propensity to hire and fire, and thus on employment levels. Further, they also find that firing costs slightly increase average long-run employment. Subsequent to the oil shock, firms were not able to fire as they would have due to high firing costs.\footnote{\citet{Blanchard1997} also shows that wages failed to adjust to the productivity slowdown and adverse supply shocks of the 1970s. Thus, wages remained relatively high and so did the labor share. This phenomenon was more pronounced in Continental European countries than in the Anglo-Saxon countries, mainly due to labor market institutions.} They reduced employment with attrition, thus the process took time and the employment remained higher than it should during some years. In addition, most of the employment security policies were introduced between the 1960s and the beginning of the 1970s. Here again, these protections may be the result of the baby-boomers generation operating a political pressure to secure employment. Although, I do not integrate it in the model. Then, France during the 1980s has started to implement policies in order to make the labor market more flexible. For instance, short term contracts have been introduced in 1979. To summarize, the labor market institutions in France were tremendously different before and after the 1980s. The reason why the model prediction does not reproduce the labor share in the data owes to the calibration of the model that is in line with the labor market institutions after 1980, but not before. Another way to think about it, in terms of the model, is to suppose that the capital-labor elasticity of substitution was much smaller before 1980.\footnote{Perhaps even lower than 1, meaning that an increase in \(k_t\) leads to an increase in \(\theta_t\).} Therefore, the representative firm was constrained and not able to substitute labor by capital as much as the model predicts.
In line with the above arguments, I investigate whether there is a change in the regime of \(\sigma\) over this period. Details of the methodology are provided in \href{app-D}{appendix D}. I find that such a break has occurred during the 1980s in France.

To highlight the mechanisms of the declining labor share, it is necessary to look at the variations of determinant variables.
Figure \ref{fig:dev7010} displays the deviation from the 1970's value of determinant variables in percentage.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/dev7010-1} 

}

\caption{Deviation from the initial value of the determinant variables}\label{fig:dev7010}
\end{figure}

The equilibrium of the economy is determined by the interaction of the wage bargaining and the voting. Both processes take place simultaneously. The demographic context over this period is presented in figure \ref{fig:demo}. The population growth \(n_t\) slightly exceeds the increasing survival rate \(p_t\) between 1970 and 2000. Thus, the old-age-dependency ratio \(p_t/n_t\) remains roughly constant. With a decline in France in 1980 due to the massive entry of the baby-boomers in the labor force. The old-age-dependency ratio starts to increase between 2000 and 2010 due to a steady population growth but a sharply increasing survival rate. This increase is also due to the baby-boomers' cohort starting to retire. As a result of this demographic context, the youth political weight \(\eta_t\) was above its 1970's level until 2000 in both countries.

As the youth's political weight rises and because they desire more redistribution, the tax rate \(\tau_t\) increases. Due to the opportunistic behavior of political parties, pro-youth policies are implemented. In the model, pro-youth policies correspond to pro-labor policies and are translated in terms of unemployment benefits in order to insure the unemployment risk. Thus, the unemployment benefits share in government revenue increases at the cost of the government health spending share in government revenue. These policy changes interact with the wage bargaining because they affect the outside option of the young agents. Pro-youth public policies motivated by a higher youth political weight leads to an increase of the unemployment benefits and a decline of the disposable income rate \((1-\tau_t)\). These two variables determine the outside option \(b_t/(1-\tau_t)\) within the wage bargaining. The decrease of the denominator exceeds the increase of the numerator. Thus, the net effect on the outside option is positive and allows workers to bargain a greater wage \(w_t\). The gain in net wage \((1-\tau_t)w_t\) exceeds the one in unemployment benefits per capita \(b_t\). Hence, employment is even more worth as unemployment in terms of utility, i.e.~\(dX_t > 0\). Due to the ability of workers to bargain a greater wage, the representative firm shifts away from labor. This behavior is permitted by two features of the model. First, the right-to-manage specification of the wage bargaining enables the firm to hire and fire as much as wanted. Second, the capital-labor elasticity of substitution \(\sigma\) is greater than unity for both countries. Thus, both input factors are gross substitutes. The firm is able to substitute labor with capital for a given output level. This behavior leads to a decline of the number of workers \(L_t\) because the labor cost (i.e.~the wage) has increased. Notice that the substitution effect is more vigorous in France because of the relatively higher elasticity of substitution \(\sigma\). The French economy has a faster growth in capital stock \(K_t\), while French firms are able to substitute relatively more labor with capital. Thus, the number of workers becomes lower than its 1970's level in France. While the United-States manage to slightly increase its labor factor. As a consequence, the US output \(Y_t\) grows faster.
The slowdown in employment has consequences on the labor market.
This slowdown in employment directly raises unemployment in France by reducing the number of workers. Furthermore, the effect is all the more tremendous because the labor force \(N_t^y\) grows due to the baby-boomers' arrival. The United-States also know a growing population but the impact on unemployment is much weaker due to the increasing number of workers, as discussed above.
The dynamics of the production function affects the determinants of the labor share.
Due to the fact that both input factors are gross substitute, the output-per-worker \(Y_t/L_t\) increases when the capital-per-worker \(k_t\) does so. This increase exceeds the one of the wage. As a result, the labor share declines.
Let us summarize the mechanisms over this period. The baby-boomers change labor market institutions in their favor due to their relatively high political weight. It raises the outside option of workers, giving more bargaining power to the union who is able to bargain greater wages. The cost of labor becoming too high, the firms decide to shift away from labor. The fact that both input factors are gross-substitutes allows firms to substitute labor with capital. The shift away from labor engenders an increase in output per worker which thwarts and exceeds the wage gain. Thus, the labor share declines.

\hypertarget{pred1080}{%
\subsection{Model predictions over the period 2010-2080}\label{pred1080}}

Figure \ref{fig:baseline1080} displays the labor share predicted by the model for the period 2010-2080.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/baseline1080-1} 

}

\caption{Model prediction of the labor share (2010-2080)}\label{fig:baseline1080}
\end{figure}

The model predicts that the labor share should continue to decline after 2010 in both countries. However, France should face a slight rise in 2030 up to 66.1\% before shrinking again. While the US labor share should remain stable around 62.6 \% between 2010 and 2040 and then follows the same pattern. Figure \ref{fig:dev1080} displays the deviation from the 1970's value of determinant variables in percentage.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/dev1080-1} 

}

\caption{Deviation from the initial value of the determinant variables}\label{fig:dev1080}
\end{figure}

The demographic context over the period 2010-2080, as presented in figure \ref{fig:demo}, is roughly the same for France and the United-States in terms of dynamics. Although the magnitudes are not similar. The population growth \(n_t\) faces a sharp decline between 2010 and 2050 before stabilizing thereafter. Meanwhile, the survival rate \(p_t\) grows by around 4\% per decade. Thus, the old-age-dependency ratio increases up to 2050, more in France than in the United-States. Once the population growth becomes stable, the ratio still grows but at a lower rate. This aging of the population is mainly due to the baby-boomers' retirement. As a result, the youth political weight never gets back to its 2010's level and will strongly decline up to 2050 for both countries.

The young political weight \(\eta_t\) sharply declines due to the aging of the population. Thus, opportunistic political candidates favor old individuals who desire less redistribution, i.e.~\(\partial\tau_t / \partial \eta_t > 0\). Pro-elderly public policies are implemented. In terms of the model, it is translated by an increase of the health spending share in government revenue at the cost of the unemployment benefits one.
These policy changes interact with the wage bargaining because they affect the outside option of young households.
Pro-elderly public policies leads to slightly weaken the outside option \(b_t/(1-\tau_t)\) within the wage bargaining for both countries between 2010 and 2050. Workers are no longer in position to bargain greater wages and have to concede a wage cut. But the declining wage goes along with a lowering of the tax rate which diminishes the impact on the net wage. Hence, having a job between 2010 and 2050 is worth less in terms of utility than it was in 2010. In both countries, the outside option rises over the period 2050-2080 and so does the bargained wage. This increase is mainly due to the disappearance of baby-boomers. Thus, the age-related conflict within the public policy becomes relatively more in favor of the youth again.
As the wage decreases between 2010 and 2050, the representative firm has incentive to hire. Thus, the labor \(L_t\) does increase over this period. Meanwhile, the capital stock \(K_t\) has increased due to savings \(S_t\) of the previous periods. Thus, both factors increase and so does the output \(Y_t\). After 2050, France and the United-States diverge in their trajectories. On one hand, the US capital stock rises due to high savings of the previous periods.\footnote{This increase in savings owes to the baby-boomers cohort when they were young. Their massive entry on the labor market, rising expected life expectancy and higher wages have fostered savings and therefore the capital available in the economy once old.} This rise is strong enough to foster the representative firm to hire workers. Thus, the substitution mechanism does not operate. On the other hand, the increase of the French capital stock does not follow the same exploding pattern. The french representative firm, as during the end of the twentieth century, shifts away from labor and decreases the number of workers. This divergence also appears on the labor market.
The labor force \(N^y_t\) is roughly constant over the whole period and France is even below its 2010's level. Thus, variations in the number of workers mainly drives the unemployment ones. The unemployment rate decreases in the United-States over the whole period. It falls down to 1.69\% by 2080 against 44.6\% in 2010. Here again, the sharp increase of the capital stock fosters employment until almost full-employment. The French unemployment rate decreases until 2050 before to slightly rise a bit and stabilize itself around 26.9\% in 2080.
French and US workers experience a minor reduction of their wage \(w_t\) between 2010 and 2050 and so does the output per worker \(Y_t/L_t\). The latter being greater than the former, the French labor share slightly increases. The US labor share remains constant because both variations compensate. After 2050, both labor shares decline to reach 62\% and 59.8\%, respectively for France and the United-States. While their respective levels in 2010 were 65.1\% and 62.5\%.

\hypertarget{counterfactual}{%
\subsection{Counterfactual and aging effect decomposition}\label{counterfactual}}

So far, I have highlighted the different mechanisms through which the age structure of the population affects economic variables and therefore the labor share. I now consider the previous model's prediction as the benchmark prediction. For the French case, I envisage the model specification with a break in the regime of \(\sigma\). To summarize, demographic changes are due to two determinant variables in the model : the population growth \(n_t\) and the survival rate \(p_t\). These variations may affect the labor share through two channels : the direct cohort effect and the indirect cohort effect \(\eta_t\).

I make counterfactual predictions in order to quantity the respective role of each channel. The idea is to neutralize either a determinant of the demographic change or a channel through which the labor share is affected. The intuition behind the counterfactual is to observe what would have happened in terms of model predictions if this effect/channel was neutralized. By comparing a counterfactual simulation to the benchmark one, I can quantify its extent. I proceed in two steps. First, I examine the impact of the different determinants of demographic changes (i.e.~\(n_t\) versus \(p_t\)). Second, I investigate through which channels it occurs (i.e.~direct versus indirect).

\hypertarget{srpg}{%
\subsection{Survival rate and population growth effects}\label{srpg}}

To neutralize the impact of the survival rate \(p_t\), I assume that it remains at its 1970's level. Thus, \(p_t = p_{1970}\) and \(p_{t+1} = p_{2010}\). Population size is recalculated such that \({N^o_t}^\prime = N_t^o\times\frac{p_{1970}}{p_t}\). Moreover, \(\eta_t = \frac{n_t}{p_{1970}}\frac{1+\alpha p_{2010}}{\omega}\).
The other demographic variables (i.e.~\(n_t\) and \(N^y_t\)) follow the time series of the benchmark simulation. The initial capital stocks of the four sequences are also recalculated such that \(K_0^\prime = \frac{1+\alpha p_t}{p_t}\frac{p_{1970}}{1+\alpha p_{1970}} K_0\).\footnote{Setting constant the survival rate implies changes in the saving rate through the expected survival rate \(p_{t+1}\). Thus, \(K_0 \equiv S_{-1} = \frac{\alpha p_0}{1+\alpha p_0}\left[(1-\tau_{-1})w_{-1}(1-u_{-1})+b_{-1}u_{-1}\right]N_{-1}^y\). In order to assess the true impact of the survival rate, it is also necessary to consider saving rate changes in the counterfactual simulation. Thus, the initial capital stocks for the first periods of the four sequences becomes \(K_0^\prime = \frac{1+\alpha p_t}{p_t}\frac{p_{1970}}{1+\alpha p_{1970}} K_0\). Notice that a change in the survival rate \(p_0\) should also affect the aggregated disposable income of young households in \(t=-1\), i.e.~\((1-\tau_{-1})w_{-1}(1-u_{-1})+b_{-1}u_{-1}\). However, I do not consider this source of change. Notice also that the term \(N_{-1}^y\) does not change because \(N_{-1}^y = \frac{N_0^o}{p_0} = \frac{{N_0^o}^\prime}{p_{1970}}\).} The methodology is analogous to neutralizing the impact of the population growth but with \(n_t = n_{1970}\), \({N_t^y}^\prime = N_t^y\times\frac{n_{1970}}{n_t}\) and \(\eta_t = \frac{n_{1970}}{p_t}\frac{1+\alpha p_{t+1}}{\omega}\).\footnote{In this specification, the initial capital stocks are not changed because \(n_0\) does not affect \(S_{-1}\).} Finally, a last counterfactual is made to neutralize both effects. So, \(p_t = p_{1970}\), \(p_{t+1} = p_{2010}\), \(n_t = n_{1970}\) and \(\eta_t = \eta_{1970}\). As before, population sizes and initial capital stock values are recalculated.
Here, the old-age-dependency ratio remains constant. Table \ref{tab:demo70} summarizes the demographic variables in 1970.

\begin{table}[t]

\caption{\label{tab:demo70}Demographic variables in 1970}
\centering
\begin{tabular}{llrr}
\toprule
 & Variable & France & United States\\
\midrule
$p_{1970}$ & Survival rate in 1970 & 0.417 & 0.476\\
$n_{1970}$ & Population growth in 1970 & 1.134 & 1.597\\
$p_{2010}$ & Expected survival rate in 2010 & 0.583 & 0.561\\
$\frac{p_{1970}}{n_{1970}}$ & Old-age-dependency ratio in 1970 & 0.368 & 0.298\\
$\eta_{1970}$ & Youth political power in 1970 & 3.846 & 3.008\\
\bottomrule
\end{tabular}
\end{table}

Figure \ref{fig:counter-pgsr} displays the model predictions of the labor share with counterfactual specifications.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/counter-pgsr-1} 

}

\caption{Model predictions of the labor share with counterfactual specifications}\label{fig:counter-pgsr}
\end{figure}

To interpret the role played by each demographic variable, I compare each counterfactual time series to the benchmark one. For instance, let us start with the impact of the survival rate in France. I look at the dashed curve with respect to the solid one. This curve corresponds to the counterfactual where the survival rate \(p_t\) and \(p_{t+1}\) remain at their 1970's levels. So, if the survival rate would have not changed, then the labor share would have followed the dashed curve pattern.
The dashed curve lies below the solid one. Therefore, the survival rate dynamic has a positive impact on the labor share in both countries.
The way to interpret the other counterfactuals is similar.
The dash-dotted curve remains above the solid one until 2050 for France and 2030 for the United States. Until these years, the population growth dynamic has a negative impact on the labor share and a positive one thereafter.
Finally, the dotted curve which corresponds to the counterfactual where both effects are neutralized is below the benchmark simulation. Since 1970, all demographic dynamics have led to increase the labor share with respect to what it would have been without these dynamics.
However, this representation is tediously legible. Therefore, I compute the distance between the benchmark labor share and each counterfactual labor share. Using the Chasles' relation within an affine space at each point in time, it is possible to isolate the extent of each effect.\footnote{Let \(r\) (resp. \(b, g, p\)) be the labor share from the red (resp. blue, green, purple) curve on figure \ref{fig:counter-pgsr}. For a given year, \(2\vec{rp} = \vec{rb} + \vec{bp} + \vec{rg} + \vec{gp} \Leftrightarrow \vec{rp} = \vec{rb} + \vec{rg} + \vec{\text{int.}}\), where \(\vec{\text{int.}} \equiv \vec{bp} + \vec{gp} - \vec{rp} = \vec{gp} +\vec{br} = \vec{bp} + \vec{gr}\) is the interaction of both effects defined as the part which is not exclusively explained by both effects independently.} Figure \ref{fig:decomp-pgsr} displays the labors share's gap between the benchmark and the counterfactuals in percentage points.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/decomp-pgsr-1} 

}

\caption{Aging-effect decomposition by determinant}\label{fig:decomp-pgsr}
\end{figure}

As mentioned above, the survival rate effect has kept the labor share relatively high in both countries. Another way to think about that is to consider demographic dynamics in terms of cohort sizes. Until 2010, if the survival rate had been held constant, then the massive increase in the population of young households due to the baby-boomers' presence would have generated an even larger decline of the labor share. However, the aging population (i.e.~the increase of the survival rate) has thwarted part of this fall. Notice that the difference with the counterfactual is less than 1\% in the case of the United-States. It suggests that the aging phenomenon over this period is a larger determinant of the labor share in France compared to the United-States.
The analysis of the determinants only reveals part of the explanation. It is also necessary to look at the channels that affect the labor share.

\hypertarget{direct-and-indirect-cohort-effects}{%
\subsection{Direct and indirect cohort effects}\label{direct-and-indirect-cohort-effects}}

To neutralize the indirect cohort effect, I fix the youth political weight \(\eta_t\) to its 1970's value but I keep the demographic variables' time series \(n_t\), \(p_t\) and \(p_{t+1}\) as in the benchmark simulation. Thus, \(\eta_t = \eta_{1970}\). To neutralize the direct cohort effect, I assume that all the demographic variables remain at their 1970's level. Thus, \(p_t = p_{1970}\), \(p_{t+1} = p_{2010}\), \(n_t = n_{1970}\) and population sizes but also initial capital stocks are recalculated. But the youth political weight time series \(\eta_t\) is the one of the benchmark simulation. Finally, a last counterfactual is made where I neutralize both effects.\footnote{This last specification is the same as in the survival rate and population growth effects decomposition. So the purple curve in figure \ref{fig:counter-pgsr}.}

Figure \ref{fig:counter-deie} displays the model predictions of the labor share with counterfactual specifications.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/counter-deie-1} 

}

\caption{Model predictions of the labor share with counterfactual specifications}\label{fig:counter-deie}
\end{figure}

The methodology to interpret this figure is similar to the one of the figure \ref{fig:counter-pgsr}. The dash-dotted curve corresponds to the direct cohort effect. For both countries, this curve is below the benchmark curve until 2010 and above thereafter. It means that the demographic dynamics' net impact through the direct channel is positive on the labor share until 2010 and negative thereafter. Looking at the dashed curve, it is slightly above before 2000 and largely below thereafter. The net impact of the indirect cohort effect is negative up to 2000 and positive subsequently. However, this representation is also tediously legible. Therefore, I isolate the extent of each channel with the same methodology as before. Figure \ref{fig:decomp-deie} displays the labor share's gap between the benchmark and the counterfactuals in percentage points.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/decomp-deie-1} 

}

\caption{Aging-effect decomposition by determinant}\label{fig:decomp-deie}
\end{figure}

The direct cohort effect is positive when the baby-boomers are young and after becomes negative. While the indirect cohort effect has the opposite pattern. The direct cohort effect dominates the indirect one until 2010 before to become less influential. Until 2010, if the demographic variables had been held constant, then the relatively high political power of the youth due to the baby-boomers' presence would have generated an even larger decline of the labor share. However, the aging population was mainly driven by the increasing survival rate which has thwarted part of the fall. Notice that, here again, the difference with counterfactual is less than 1\% in the case of the United-States. It suggests that the aging phenomenon over this period is a larger determinant of the labor share in France compared to the United-States.
After 2010, so once the baby-boomers' cohort retires, the model predicts that the indirect cohort effect (i.e.~the decline of the youth political power) should exceed the direct one. This is directly related to the mechanism analysis of section \ref{pred1080}. The baby-boomers and more generally the old households becomes the winners of the age-related conflict within the public policy over this period. Thereby, they reduce the workers' outside option which leads to a wage cut or more precisely to a wage stagnation. The labor cost remains constant while the capital available in the economy accumulates. It generates an incentive for the representative firm to hire more workers. As a result, the labor share increases.

\hypertarget{summary}{%
\subsection{Summary}\label{summary}}

Figure \ref{fig:decomp-country-period} summarizes the aging-effect decomposition by period and country.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/decomp-country-period-1} 

}

\caption{Aging-effect decomposition by period and country}\label{fig:decomp-country-period}
\end{figure}

The main determinant of the aging phenomenon is the survival rate. On average, it explains 54.5\% for France and 78.1\% for the United-States of the impact on the labor share over the period 1980-2010. This decomposition persists thereafter. However, the channel decomposition does not. Between 1980 and 2010, demographic dynamics affect the labor share mainly through the direct channel in France. While the indirect one is dominant in the United-States. On average, the share explained by the direct cohort effect is about 53.1\% for France and 38.2\% for the United-States. However, over the next period, the direct cohort effect is not the dominant channel anymore in France. It falls to 20.3\%, suggesting that the indirect cohort effect becomes the main carrier of the demographic dynamics on the labor share. In contrast, it remains relatively stable in the United-States, at around 35.7\%.

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}

\hypertarget{winners}{%
\subsection{Age-related conflict: who are the winners ?}\label{winners}}

So far, the labor share has been declining due to the baby-boomers generation in both countries. First, when they were young because they shaped the public policy and so the labor market institutions in their favor. The firms answered to that by substituting labor to capital. Second, when they were old because they have considerably increased the available capital in the economy through savings allowing the firms to substitute even more. However, the labor income share is a gross indicator of inequalities. A more appropriate indicator may be the income ratio between young and old after redistribution.

From equation \eqref{eq:after-tax-income-ratio}, I have that the after-tax young-to-old income ratio is equal to the young political weight (i.e.~\(Y_t^y/Y_t^o = \eta_t\)). While the before-tax young-to-old income ratio corresponds to the labor-to-capital ratio (i.e.~\(\Theta_t = \frac{w_tL_t}{r_tK_t}\)). Figure \ref{fig:raw-vs-net-inc-ratio} displays these income ratios in deviation from the 1970 steady-state.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/raw-vs-net-inc-ratio-1} 

}

\caption{Deviation from 1970 value of the labor-to-capital income ratio and the young-to-old income ratio}\label{fig:raw-vs-net-inc-ratio}
\end{figure}

While the labor share and so the labor-to-capital ratio (i.e.~before-tax young-to-old income ratio) sharply decline between 1970 and 2000, the after-tax young-to-old income ratio lies over its 1970's level during the same period. Even if I include the government health spending as part of the old households income, the young-to-old income ratio remains over its initial level until 2000.\footnote{In terms of deviation, the curve is combined with the dashed one.} This model prediction holds for both countries. The baby-boomers gross income share (i.e.~labor income share) has declined due to the mechanisms previously mentioned when they were young. However, they also have spurred political parties to implement redistributive public policies.\footnote{This is the result of the probabilistic voting specification. The opportunist behavior of political parties lead them to favor this generation in order to maximize their probability to win the election.} This redistribution is characterized, in terms of the model, through a raise of the tax rate and an increase of the unemployment spending share within the government revenue.\footnote{Notice that the increase of the unemployment spending share is driven and accentuated by the raising unemployment due to factor substitution.} Thus, they have been able to seize part of their elders income through redistribution. Even though baby-boomers appeared as income losers over this period because the labor share was falling, they are actually the winners once net income is considered.

Another way to determine the winners of the age-related conflict within the public policy is to look how the GDP is allocated in the economy. Figure \ref{fig:redis-step3-stacked} displays the income allocation after redistribution.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/redis-step3-stacked-1} 

}

\caption{After-tax income share allocation}\label{fig:redis-step3-stacked}
\end{figure}

The dashed curve corresponds to the labor share, so the before-tax young income share. As long as this curve lies in the area of the government unemployment spending share, it means that old agents fund unemployment spending through their taxes. On the contrary, when the dashed curve lies in the area of the government health spending share, the young agents fund government health spending for their elders. The US share of GDP which is allocated to health spending is quite small compared to the French one. This is directly related to the preference parameter for government health spending \(\beta\).\footnote{\(\beta_{\text{FR}} = 0.739\) and \(\beta_{\text{US}} = 0.138\).} The US young generations are the winners of the age-related conflict from 1970 to 2020 which corresponds to the active period of the baby-boomers. Once the US population ages and therefore the baby-boomers, old households dominates the public policy conflict. However, the size of the government revenue declines due to the fact that the United-States converges to full employment in the long run. For France, the baby-boomers also dominate the public policy conflict between 1990 and 2010 when they are active. Once they retire, so over the period 2010-2040, they are still the winners of this conflict and their children fund government health spending. Notice that the size of the welfare state corresponds to the sum of the unemployment benefits share in GDP and the health spending share in GDP.

\hypertarget{retirement}{%
\subsection{Retirement age}\label{retirement}}

So far, I have not discussed the retirement age and its implications on the labor share.
As mentioned in the introduction, the relationship between aging and economic growth has received much more attention than the one with the labor share. \citet{Gonzalez-Eiras2012} predict that the retirement age in OECD countries should increase in response to population aging. In their model of politico-economic equilibrium, individuals vote with perfect foresight and decide to raise retirement age as long as population ages. Agents work longer and so accumulate more wealth, it reduces social-security transfers and thereby releases more government spending to public investment which is an engine for growth.\footnote{However, this result contrasts with \citet{Jager2016} who find out that the share of elderly people and public investment are negatively co-integrated. They use panel data of 19 OECD countries from 1971 to 2007. This gap may be due to two reasons: \emph{i)} some public policy instruments which are not considered in the model of \citet{Gonzalez-Eiras2012} might invert the relationship between aging and public investment; \emph{ii)} the perfect foresight assumption might be too strong. Both potential explanations may reconcile these diverging results.} On the contrary, \citet{Futagami2001} claim that population aging does not necessarily depress economic growth and may even foster it through savings. Thus, postponing the retirement age would result in a decline of savings and so the economic growth. \citet{Dedry2017} also discuss the role of legal retirement age according to the type of pension system in a context of population aging due to either declining fertility or increasing longevity.

In order to take into account the role of retirement age, I perform counterfactual predictions with different scenarii based on an exogenous change. The retirement age is captured within the variable \(p_t\) which depends negatively on it but positively on the life expectancy. I do not endogenize this variable due to the limited form of rationality and to the several assumptions that would be required.\footnote{To have an endogenous retirement age, agents should vote on it and thereby vote on the survival rate. The first question would be to determine whether agents vote on \(p_t\), \(p_{t+1}\) or both. Then, the perfect annuity market would have a lot of implications on the results. Since savings of young agents who die before reaching old age are distributed among their surviving peers, it means that an agent has an incentive to vote for a decline of the survival rate because fewer peers would reach old age. Thus, it would increase its income and so its utility. Therefore, it would be necessary to determine whether or not agents internalize the perfect annuity market in their voting decisions.} In the public debate, it is often argued that the legal retirement age should change in the future, usually upward, as claimed by \citet{Gonzalez-Eiras2012}.
. Between 2020 and 2030, I suppose a positive exogenous shock on the age of retirement. Meaning that less individuals would reach the old age which is translated into a decline of the survival rate, i.e.~\(p_t\). As in section \ref{counterfactual}, other demographic variables have to be changed for the period following the shock of each simulation's sequence (i.e.~2030, 2040, 2050 and 2060). However, the implications for demographic dynamics are not identical to this previous exercise. Because the greater the retirement age, the longer an individual remains young in terms of the model. Thus, these individuals do not vanish but just remain longer in the labor force.\footnote{In the same way, the capital stock of these periods is not changed as in section \ref{counterfactual} because it has already been accumulated through savings from previous periods. It has no reason to vanish or to be scraped.}
Therefore, conjointly with the decline of the survival rate, there is a share of the young population that does remain young.
From the identity \(\frac{N_t^o}{N_t^y} \equiv \frac{p_t}{n_t}\), I obtain:
\begin{equation}
    \frac{\dot{N}_t^o}{N_t^o} - \frac{\dot{N}_t^y}{N_t^y} = \frac{\dot{p}_t}{p_t} - \frac{\dot{n}_t}{n_t} \label{eq:demo-growth-identity}
\end{equation}
where the upper dotted variables correspond to the variables' variation, e.g.~\(\dot{N}_t^o = {N_t^o}^\prime - N_t^o\) where \({N_t^o}^\prime\) is the new value for \(N_t^o\). This equation has to be satisfied. The exogenous shock on \(p_t\) affects all other demographic variables. Firstly, the size of the old population varies as much as the survival rate does, i.e.~\(\frac{\dot{N}_t^o}{N_t^o} = \frac{\dot{p}_t}{p_t}\). Secondly, the variations of the young population's size are inversely proportional to the ones of the old population size, i.e.~\(\frac{\dot{N}_t^y}{N_t^y} = -\frac{\dot{N}_t^o}{N_t^o}\). Thirdly, by taking into account the two previous points and the fact that equation \eqref{eq:demo-growth-identity} has to be satisfied, it implies that \(\frac{\dot{n}_t}{n_t} = -\frac{\dot{p}_t}{p_t}\). Therefore, the exogenous shock on \(p_t\) affects the other variables with the same magnitude.
Hence,
\begin{align*}
    \dot{N}^o_t = \frac{\dot{p}_t}{p_t} N^o_t \implies& {N^o_t}^\prime = \left(1+\frac{\dot{p}_t}{p_t}\right) N^o_t \\
    \dot{N}^y_t = -\frac{\dot{p}_t}{p_t} N^y_t \implies& {N^y_t}^\prime = \left(1-\frac{\dot{p}_t}{p_t}\right) N^y_t \\
    \dot{n}_t = -\frac{\dot{p}_t}{p_t} n_t \implies& {n_t}^\prime = \left(1-\frac{\dot{p}_t}{p_t}\right) n_t
\end{align*}
where \(\frac{\dot{p}_t}{p_t} = \frac{p^\prime_t - p_t}{p_t} \implies p^\prime_t = p_t + \dot{p}_t\). Thus, the new demographics variables \(N^{o\prime}_t, N^{y\prime}_t, p^\prime_t, n^\prime_t\) are computed for the years 2030, 2040, 2050 and 2060. For the years 2070 and 2080: \(n^\prime_t\) follows the benchmark time series and population sizes are computed with \(N^{o\prime}_t = p^\prime_t {N^{y\prime}_{t-1}}\) and \(N^{y\prime}_t = n^\prime_t N^{y\prime}_{t-1}\). Notice that new values of the expected survival rate \(p^\prime_{t+1}\) changes according to \(p^\prime_t\). Moreover, \(\eta^\prime_t = \frac{n^\prime_t}{p^\prime_t}\frac{1+\alpha p^\prime_{t+1}}{\omega}\) is also recomputed.

Two types of scenario are possible for a change in the age of retirement between 2020 and 2030. Firstly, I consider that the retirement age increases in such a way that the survival rate is negatively affected by 10\% in 2030.\footnote{The underlying (strong) assumption of this whole exercise is that the change in retirement age has no consequences on life expectancy. Some authors argue that increasing the retirement age has a negative impact on health and so the life expectancy (see, for example, \citet{Insler2014} for the United-States; \citet{Coe2011} for Europe). Thereby, the negative effect on the survival rate may be all the more tenacious due to the declining life expectancy. Despite the presence of a potential co-integration of the retirement age and the life expectancy, I believe that the qualitative impact is not affected in the sense that the simulation is a lower bound.} Thereafter, the survival rate grows at the same growth rate as in the benchmark simulation.\footnote{I assume that the shock does not change the future growth path of the survival rate.} This first scenario can be summarized as a one-shot shift by 10\% of the survival rate. Secondly, another scenario is to consider that retirement age increases in such a way that the survival rate grows at a fraction \(\zeta \in \left[0,1\right]\) of the benchmark simulation's growth rate. The new values of the survival rate \(p^\prime_t\) after 2030 are described as follow:
\begin{equation*}
    p^\prime_t = \zeta(p_t - \bar{p}) + \bar{p}
\end{equation*}
where \(\bar{p}\) is the value of the survival rate in 2030. This can be interpreted as a gradual increase of the retirement age that is proportional to improvement in life expectancy.\footnote{When \(\zeta = 1\), the survival rate dynamic corresponds to the one of the benchmark simulation, i.e.~\(p_t^\prime = p_t\). Thus, variations are no longer proportional to changes in life expectancy. While when \(\zeta = 0\), the survival rate remains constant, i.e.~\(p_t^\prime = \bar{p}\) after 2030. In such a case, variations in retirement age are fully proportional to the ones in life expectancy.} Such dynamics imply perfect forecasts on life expectancy which are assumed in this model.

Figure \ref{fig:retage-p} displays the survival rate dynamics with changing retirement age specifications for both countries.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/retage-p-1} 

}

\caption{Survival rate dynamics with changing retirement age specifications}\label{fig:retage-p}
\end{figure}

The dashed curves correspond to the first scenario mentioned above where the survival rate is shocked by -10\% in 2030 and keeps its growth rate thereafter. The dash-dotted and dotted curves are two special cases of the second scenario. The dashed-dotted curves refers to the case where \(\zeta = 0\), so the survival rate remains constant after 2030. It means that variations in retirement age are fully proportional to those in life expectancy. While the dotted curves coincide to the case where \(\zeta = .5\). Thus, the survival rate \(p_t\) grows at half of the speed of the benchmark simulation.

Figure \ref{fig:retage_ls} displays model predictions of the labor share according to the scenario.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/retage-ls-1} 

}

\caption{Model predictions of the labor share with changing retirement age specifications}\label{fig:retage-ls}
\end{figure}

The raise of the age of retirement in France leads to a decline of the labor share with respect to the benchmark simulation in a first phase. In a second phase, the very long-run, the labor share is relatively greater than in the benchmark case. This result holds regardless of the scenario. In the United-States, the impact on the labor share depends on the scenario. As in France, the -10\% shift scenario generates a sharper decline of the labor share before to exceed the benchmark simulation's one in the very long-run. However, both scenarii of diminished growth of the survival rate have roughly the same pattern of the benchmark labor share. But there are still above the labor share in the very long-run. Therefore, changing the retirement age may have different impact on the labor share according to the country.

The underlying mechanisms are related to those detailed in section \ref{quantitative}. However, there is a particularity to this change of the retirement age. The capital stock does not immediately adjust in the model. Because it has been determined by the savings of the previous period of each sequence, where the expected survival rate \(p_{t+1}\) was much greater than the after-reform one \(p^\prime_{t+1}\). This specificity cancels part of the direct cohort effect. This relatively high amount of available capital stock plays in favor of the firm within the wage bargaining. Because the firm is all the more able to substitute labor with capital. On the indirect cohort effect's side, the agents remain young longer due to the increase of the retirement age. This is translated in terms of the model with a decrease of the number of old households and an increase of the number of young households. Thus, the youth has more political weight than in the benchmark case. With this political strength, they raise their outside option through pro-young public policies which allows them to bargain greater wages. As a response, the firm shift away from labor and hire relatively less workers than in the benchmark case. As mentioned above, the relatively high amount of available capital stock due to the \emph{stickiness} enables the firm to substitute all the more.

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

The literature on the labor share has emphasized the role of factors such as biased technical change or labor market institutions in shaping its changes over time.
In this paper, I explore an alternative mechanism focusing on inter-generational conflict and policy choices.
I build an OLG model in which labor market institutions are endogenously determined through public policy and affect the wage bargaining.
Using this model, I analyze the impact of demographic dynamics on labor share's long-term dynamics in France and the United-States.
Numerical simulations are able to replicate the data for both countries since the 1970s.

Model predictions suggest that the decline of the labor share during the last decades was driven by cohort-size effects.
For France, the baby-boomers cohort seems to drive public policy and thus the way in which national income is allocated between labor and capital.
When the baby-boomers cohort enters on the labor market, they shape labor market institutions in their favor because they face an unemployment risk, as opportunistic political candidates implement the policy desired by this cohort.
These more protective labor market institutions raise workers' outside option, enables unions to bargain greater wages, and induce firms to use more capital as long as factors are gross substitutes.
The unemployment rate rises and so does the output per worker, offsetting the increase in the wage rate.
Therefore, the labor share declines over the end of the twentieth century.
Thereafter, the baby-boomers retire and trigger the opposite mechanism.
Although the public policy shrinks the outside option of workers within the wage bargaining which should reduce wages and raise employment.
The capital stock has sharply increased due to massive savings of the baby-boomers when they were young.
The important available capital stocks partially thwart the reverse mechanism and the labor share does not recover its past level.
The model predicts a slight resurgence of the labor share for the next decades in France and a stagnation in the United-States.

Counterfactual decomposition suggest that the survival rate dynamics have a larger impact on the labor share than the population growth dynamics. I also decompose this impact between two channels: the direct cohort-size effect and the indirect cohort-size effect. The former dominates for France when the baby boomers are young, while the latter takes the lead once this cohort retires. Although the labor share declined due to public policies implemented by baby boomers, they managed to increase their after-tax income through redistribution. An increase of the retirement age should decrease the labor share in the following decades due to the over-accumulation of capital and the raising political power of the youth. However, the labor share is expected to be greater in the very long-run.

The two main hypothesis of the paper concern the elasticity of substitution between capital and labor and the right-to-manage specification for the wage bargaining. Recent estimates suggest that this elasticity may be greater than one \citep[see][]{Karabarbounis2014} but others have found it below one, particularly for the United-States (see, for example, \citet{Antras2004}; \citet{Chirinko2008}). Moreover, I do not include any form of biased technical change within the model. This is voluntary in order to develop an other theory on the labor share's decline based on demographic dynamics. It could be the case that biased technical change is also driven by demographic dynamics through the \emph{grability} of workers to seize part of the rent. This grability may be generated by some cohorts which are sufficiently numerous to shape labor market institutions in their favor and therefore in favor of labor. I leave the investigation of a potential endogenous biased technical change induced by demographic dynamics for further research.

\singlespacing

\hypertarget{refs}{}

\hypertarget{appendix-appendix}{%
\appendix}


\hypertarget{uniqueness}{%
\section{Uniqueness of the equilibrium}\label{uniqueness}}

Let us define, respectively, equations \eqref{eq:Xg} and \eqref{eq:Xh} with the functions \(g(k_t, N_t^y, K_t, \eta_t; \phi, \sigma)\) and \(h(k_t ; \gamma, \phi, \sigma)\) such as:
\begin{align*}
        g(k_t, N_t^y, K_t, \eta_t; \phi, \sigma) &= \ln\left( \frac{ \frac{N_t^y}{K_t} k_t - 1 } { \frac{\phi}{1-\phi} k_t^{\frac{\sigma-1}{\sigma}} \eta_t - 1 }\right) \\
        h(k_t ; \gamma, \phi, \sigma) &= \left( \sigma + \frac{1-\phi}{\phi} \frac{1-\gamma(1-\sigma)}{\gamma} k_t^{\frac{1-\sigma}{\sigma}} \right)^{-1}
\end{align*}

Due to the logarithm, we have two vertical asymptotes depending on whether the numerator or the denominator within the logarithm is equal to zero. The first vertical asymptote is the one associated to the numerator \(k_1 = \frac{K_t}{N_t^y}\) and the second vertical asymptote is associated to the denominator \(k_2 = \left(\frac{1-\phi}{\phi} \frac{1}{\eta_t}\right)^{\frac{\sigma}{\sigma-1}}\). Rewriting the \(g\) function with these vertical asymptotes, I have:
\begin{equation*}
  g(k_t, k_1, k_2; \sigma) = \ln\left( \frac{\frac{k_t}{k_1}-1}{\left(\frac{k_t}{k_2}\right)^{\frac{\sigma - 1}{\sigma}} - 1} \right)
\end{equation*}
This function has four different shapes according to the value of \(\sigma\) and both vertical asymptotes (\(k_1\) and \(k_2\)). Figure \ref{fig:g-shape} plots these shapes.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/g-shape-1} 

}

\caption{Different possible shapes of the g function, according to the values of $\sigma$, $k_1$ and $k_2$}\label{fig:g-shape}
\end{figure}

The \(h\) function has three different shapes according to the value of \(\sigma\). Figure \ref{fig:h-shape} plots these shapes.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/h-shape-1} 

}

\caption{Different possible shapes of the h function, according to the values of $\sigma$}\label{fig:h-shape}
\end{figure}

\BeginKnitrBlock{proposition}
\protect\hypertarget{prp:full-emp}{}{\label{prp:full-emp} }If \(k_t \leq k_1\) at the equilibrium, then there is a unique equilibrium with full employment where \(k_t = k_1\) and the net wage equals the unemployment benefits, i.e.~\((1-\tau_t)w_t = b_t\).
\EndKnitrBlock{proposition}

\BeginKnitrBlock{proof}
\iffalse{} {Proof. } \fi{}The numerator of the \(g\) function is positive if and only if \(k_t > k_1 \Leftrightarrow L_t < N_t^y\) (i.e.~the number of worker is smaller than the young population size). This condition is always satisfied when there is unemployment. However, if this condition is not satisfied, labor demand exceeds the labor force (i.e.~\(L_t^d > N_t^y\)). Therefore, the economy is in full-employment (i.e.~\(L_t = N_t^y\)) and capital-per-worker is \(k_t = k_1\). In such a case, \(X_t\) tends to \(-\infty\). However, the lower bound of \(X_t\) is \(0\). Because if \(X_t\) is negative, the unemployment benefits would exceed the net wage. I consider that such a case is not possible.\footnote{Even though I consider a model with inelastic labor supply, no agent would work for a wage which is lower than unemployment benefits. This assumption can be considered as an incentive constraint.} Thus, if \(k_t \leq k_1 \implies k_t = k_1 \implies u_t = 0 \implies X_t = 0 \implies (1-\tau_t)w_t = b_t\).
\EndKnitrBlock{proof}

Therefore, the equilibrium with unemployment requires \(k_t > k_1\). Hence, any equilibrium in the case represented in the bottom-left panel of figure \ref{fig:g-shape} leads to the equilibrium with full-employment.

I normalize \(k_t\) to the vertical asymptote \(k_1\). Let \(\nu = k_2/k_1\) with \(\nu > 0\). It implies that \(k_2 \gtreqqless k_1\) when \(\nu \gtreqqless 1\). Let \(\tilde{k}_t = k_t / k_1\) with \(\tilde{k}_t > 0\). As for \(\nu\), if \(\tilde{k}_t\) is greater than unity, then \(k_t>k_1\) and vice-versa. To simplify the notation, let \(\rho = \frac{\sigma-1}{\sigma} \in \left(-\infty, 1\right)\).\footnote{When both input factors are gross complement, the elasticity of substitution is \(\sigma \in \left(0,1\right)\) and the corresponding interval for \(\rho\) is \(\left(-\infty, 0\right)\). However, when both are gross substitute, the elasticity of substitution is \(\sigma \in \left(0,+\infty\right)\) and the corresponding interval for \(\rho\) is \(\left(0,1\right)\).} Using this specification, it is possible to rewrite \(g\) such that:

\begin{equation*}
    g(\tilde{k}_t; \nu, \rho) = \ln\left(\frac{\tilde{k}_t - 1}{\tilde{k}_t^\rho - \nu^\rho}\right) + \rho\ln\left(\nu\right)
\end{equation*}

Let also rewrite the \(h\) function such that:

\begin{equation*}
    h(\tilde{k}_t ; \tilde{\gamma}, \rho) = \left( \frac{1}{1-\rho} + \tilde{\gamma} \tilde{k}_t^{-\rho} \right)^{-1}
\end{equation*}
where \(\tilde{\gamma} \equiv \frac{1-\phi}{\phi} \frac{1-\gamma(1-\sigma)}{\gamma} k_1^{-\rho}> 0\).

\hypertarget{under-gross-complementarity-i.e.-rho-0}{%
\subsection{\texorpdfstring{Under gross-complementarity, i.e.~\(\rho < 0\)}{Under gross-complementarity, i.e.~\textbackslash rho \textless{} 0}}\label{under-gross-complementarity-i.e.-rho-0}}

\(g(\tilde{k}_t)\) is define and continuous between both vertical asymptotes within the logarithm, so \(1\) and \(\nu\).\footnote{These vertical asymptotes correspond to \(k_1\) and \(k_2\) before the normalization.} When \(\nu\) is greater than unity, \(g(\tilde{k}_t)\) is defined and continuous on \(\left(1, \nu\right)\). While the function is defined and continuous on \(\left(\nu, 1\right)\) when \(\nu < 1\). Finally, when \(\nu = 1\), \(\tilde{k}_t\) can take a unique value which corresponds to \(1\). This definition domain is due to the properties of the logarithm. Both parts of the product within the logarithm must have the same sign in order to remain defined. The \(g\) function has two possible shapes according to the value of \(\nu\) with respect to unity:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  if \(\nu > 1\):
  + \(g(\tilde{k}_t)\) is strictly increasing in \(\tilde{k}_t\),\% i.e.~\(\frac{\partial g}{\partial \tilde{k}_t} > 0\),
  + \(\lim_{\tilde{k}_t\to 1} g(\tilde{k}_t) = -\infty\) and \(\lim_{\tilde{k}_t\to \nu} g(\tilde{k}_t) = +\infty\).
\item
  if \(\nu < 1\):

  \begin{itemize}
  \tightlist
  \item
    \(g(\tilde{k}_t)\) is strictly decreasing in \(\tilde{k}_t\),
  \item
    \(\lim_{\tilde{k}_t\to 1} g(\tilde{k}_t) = +\infty\) and \(\lim_{\tilde{k}_t\to \nu} g(\tilde{k}_t) = -\infty\).
  \end{itemize}
\end{enumerate}

When \(\rho<0\), the \(h\) function is defined and continuous on \(\mathbb{R}_+\) and has the following properties:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(h(\tilde{k}_t)\) is strictly decreasing in \(\tilde{k}_t\),\% i.e.~\(\frac{\partial h}{\partial \tilde{k}_t} \leq 0\),
\item
  \(\lim_{\tilde{k}_t\to 0} h(\tilde{k}_t) = 1-\rho\) and \(\lim_{\tilde{k}_t\to +\infty} h(\tilde{k}_t) = 0\).
\end{enumerate}

These properties leads to lemmas \ref{lem:rho-lower0-nu-lower1} and \ref{lem:rho-lower0-nu-higher1}. Using these intermediate results with proposition \ref{prp:full-emp}, I can prove proposition \ref{prp:rho-lower0}.

\BeginKnitrBlock{lemma}
\protect\hypertarget{lem:rho-lower0-nu-lower1}{}{\label{lem:rho-lower0-nu-lower1} } if \(\rho < 0\) and \(\nu > 1\), then it exists a unique equilibrium.
\EndKnitrBlock{lemma}

\BeginKnitrBlock{proof}
\iffalse{} {Proof. } \fi{} Let \(\rho < 0\) and \(\nu > 1\). The \(g\) function is defined and continuous in \(\tilde{k}_t \in \left(1, \nu \right)\), strictly increasing and has two infinite vertical asymptotes of opposite signs. The \(h\) function is defined and continuous in \(\tilde{k}_t \in \mathbb{R}_+ \supset \left(1, \nu \right)\), strictly decreasing and has two finite horizontal asymptotes \(1/\sigma\) and \(0\). Therefore, both functions intersect in only one point. Hence, there is uniqueness of the equilibrium.
\EndKnitrBlock{proof}

\BeginKnitrBlock{lemma}
\protect\hypertarget{lem:rho-lower0-nu-higher1}{}{\label{lem:rho-lower0-nu-higher1} }if \(\rho < 0\) and \(\nu < 1\), then it exists at least one equilibrium.
\EndKnitrBlock{lemma}

\BeginKnitrBlock{proof}
\iffalse{} {Proof. } \fi{}Let \(\rho < 0\) and \(\nu > 1\). The \(g\) function is defined and continuous in \(\tilde{k}_t \in \left(\nu, 1\right)\), strictly decreasing and has two infinite vertical asymptotes of opposite signs. The \(h\) function is defined and continuous in \(\tilde{k}_t \in \mathbb{R}_+ \supset \left(\nu, 1\right)\), strictly decreasing and has two finite horizontal asymptotes \(1/\sigma\) and \(0\). Therefore, both functions intersect in at least one point. Hence, there is at least one equilibrium.
\EndKnitrBlock{proof}

\BeginKnitrBlock{proposition}
\protect\hypertarget{prp:rho-lower0}{}{\label{prp:rho-lower0} } if \(\rho < 0\), then it exists a unique equilibrium.
\EndKnitrBlock{proposition}

\BeginKnitrBlock{proof}
\iffalse{} {Proof. } \fi{}Lemma \ref{lem:rho-lower0-nu-lower1} claims that there is a unique equilibrium when \(\nu > 1\). There is also a unique equilibrium when \(\nu = 1\). Lemma \ref{lem:rho-lower0-nu-higher1} asserts that there is at least one equilibrium when \(\nu < 1\). Yet, proposition \ref{prop:full-emp} states that any equilibrium when \(\nu > 1\) leads to the unique equilibrium with full-employment. Therefore, if \(\rho < 0\) there is a unique equilibrium.
\EndKnitrBlock{proof}

\hypertarget{under-gross-substituability-i.e-0-rho-1}{%
\subsection{\texorpdfstring{Under gross-substituability, i.e \(0 < \rho < 1\)}{Under gross-substituability, i.e 0 \textless{} \textbackslash rho \textless{} 1}}\label{under-gross-substituability-i.e-0-rho-1}}

Contrary to the previous case, \(g(\tilde{k}_t)\) is defined and continuous on \(\mathbb{R}_+\) but outside of both vertical asymptotes within the logarithm, so \(1\) and \(\nu\). When \(\nu\) is greater than unity, \(g(\tilde{k}_t)\) is defined and continuous on \((0, 1) \cap (\nu, +\infty)\). While the function is defined and continuous on \((0, \nu) \cap (1, +\infty)\) when \(\nu < 1\). Finally, when \(\nu = 1\), the function is defined and continuous on \(\mathbb{R}_+\) but has no longer infinite discontinuity. Regardless of the value of \(\nu\), \(\lim_{\tilde{k}_t\to 0} = 0\) and \(\lim_{\tilde{k}_t\to +\infty} = +\infty\). Both vertical asymptotes correspond to \(\lim_{\tilde{k}_t\to 1} g(\tilde{k}_t) = -\infty\) and \(\lim_{\tilde{k}_t\to \nu} g(\tilde{k}_t) = +\infty\). The \(g\) function has two possible shapes according to the value of \(\nu\) with respect to unity.\footnote{Excluding the case where \(\nu=1\).} Moreover, \(g(\tilde{k}_t)\) is strictly increasing in \(\tilde{k}_t\) when \(\nu < 1\). When \(\rho > 1\), the \(h\) function is defined and continuous on \(\mathbb{R}_+\) and has the following properties:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(h(\tilde{k}_t)\) is strictly increasing in \(\tilde{k}_t\),
\item
  \(\lim_{\tilde{k}_t\to 0} h(\tilde{k}_t) = 0\) and \(\lim_{\tilde{k}_t\to +\infty} h(\tilde{k}_t) = 1-\rho\).
\end{enumerate}

I plot both functions with numerical computation for feasible values of \(\sigma\) according to the model conditions as detailed in section \ref{wage-bargaining}. The parameters \(\gamma\) and \(\phi\) are set according to the calibration in section \ref{subsec:calibration}, thus \(\gamma = 0.5\) and \(\phi = 0.3\).\footnote{The exact values for \(\phi\) are 0.27 for France and 0.325 for the United-States. I use 0.3 for this numerical computation as an approximation of the mean.} Figure \ref{fig:uniq-d} shows both functions in the case where \(\nu < 1\).

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/uniq-d-1} 

}

\caption{Numerical simulation of g (solid line) and h (dashed line), according to the values of $\sigma$ and $\nu$}\label{fig:uniq-d}
\end{figure}

Looking at the behavior of both functions, they do intersect in only one point beyond \(1\). Therefore, I make the following conjecture:

\BeginKnitrBlock{conjecture}
\protect\hypertarget{cnj:rho-higher0-nu-lower1}{}{\label{cnj:rho-higher0-nu-lower1} }if \(\rho \in (0,1)\) and \(\nu < 1\), then it exists a unique equilibrium.
\EndKnitrBlock{conjecture}

This unique equilibrium is the one with unemployment since it lies beyond \(1\) and therefore beyond \(k_1\) without normalization. I also do the numerical computation in the case where \(\nu > 1\), with the same values for \(\gamma\) and \(\phi\). Figure \ref{fig:uniq-c} plots the result.

\begin{figure}[!tb]

{\centering \includegraphics[width=1\linewidth]{lisa_files/figure-latex/uniq-c-1} 

}

\caption{Numerical simulation of g (solid line) and h (dashed line), according to the values of $\sigma$ and $\nu$}\label{fig:uniq-c}
\end{figure}

Looking at the behavior of both functions, they do intersect two times before \(1\). Therefore, I make the following conjecture:

\BeginKnitrBlock{conjecture}
\protect\hypertarget{cnj:rho-higher0-nu-higher1}{}{\label{cnj:rho-higher0-nu-higher1} }if \(\rho \in (0,1)\) and \(\nu > 1\), then it exists at least one equilibrium lying below unity.
\EndKnitrBlock{conjecture}

Using these two conjectures with proposition \ref{prp:full-emp}, I can prove that there is a unique equilibrium for all \(\rho \in (0,1)\).\footnote{Except in the case where \(\nu = 1\), i.e.~\(k_1 = k_2\). In such a case, the infinite discontinuity disappears and so does the equilibrium.}

\BeginKnitrBlock{proposition}
\protect\hypertarget{prp:rho-higher0}{}{\label{prp:rho-higher0} }if \(\rho \in (0,1)\), then it exists a unique equilibrium.
\EndKnitrBlock{proposition}

\BeginKnitrBlock{proof}
\iffalse{} {Proof. } \fi{}Conjecture \ref{cnj:rho-higher0-nu-lower1} claims that there is a unique equilibrium when \(\nu < 1\). Conjecture \ref{conj:rho_higher0_nu_higher1} asserts that there is at least one equilibrium when \(\nu > 1\) lying below unity. Thus, there is at least one equilibrium such that \(k_t < k_1\). Yet, proposition \ref{prp:full-emp} states that any equilibrium with \(k_t \leq k_1\) leads to the unique equilibrium with full-employment. Therefore, if \(\rho \in (0,1)\) there is a unique equilibrium.
\EndKnitrBlock{proof}

\hypertarget{derivatives}{%
\section{Derivatives}\label{derivatives}}

I derive the partial derivative of both functions \(g\) and \(h\) that determine the equilibrium.

\hypertarget{the-g-functions-derivatives}{%
\subsection{\texorpdfstring{The \(g\) function's derivatives}{The g function's derivatives}}\label{the-g-functions-derivatives}}

\begin{equation*}
    g(L_t, K_t, \eta_t, N_t^y; \phi, \sigma) = \ln\left[ \frac{ \frac{N_t^y}{L_t} - 1 } { \frac{\phi}{1-\phi} \left(\frac{K_t}{L_t}\right)^{\frac{\sigma-1}{\sigma}} \eta_t - 1 }\right]
\end{equation*}
The partial derivative of the \(g\) function with respect to \(\eta_t\) is:
\begin{equation*}
        g_\eta = - \frac{\frac{\phi}{1-\phi}k_t^{\frac{\sigma-1}{\sigma}}}{\frac{\phi}{1-\phi}k_t^{\frac{\sigma-1}{\sigma}}\eta_t - 1} = - \left(\eta_t - \Theta_t\right)^{-1} < 0
\end{equation*}
where \(\eta_t/\Theta_t - 1\) corresponds to the denominator within the logarithm of the \(g\) function. At the equilibrium with unemployment, the denominator must be positive. Therefore \(\eta_t - \Theta_t >0 \implies g_\eta < 0\). The partial derivative of the \(g\) function with respect to \(N_t^y\) is:
\begin{equation*}
    g_{N^y} = \left(N_t^y-L_t\right)^{-1} > 0
\end{equation*}
At the equilibrium with unemployment, the young population size exceeds the number of workers. Thus, \(N_t^y-L_t > 0 \implies g_{N^y} > 0\). The partial derivative of the \(g\) function with respect to \(K_t\) is:
\begin{align*}
    g_K &= -\frac{1}{K_t}\frac{\sigma - 1}{\sigma}\frac{\frac{\phi}{1-\phi}k_t^{\frac{\sigma-1}{\sigma}}\eta_t}{\frac{\phi}{1-\phi}k_t^{\frac{\sigma-1}{\sigma}}\eta_t - 1} \\
    g_K &= -\frac{1}{K_t}\frac{\sigma - 1}{\sigma}\left(1-\Theta_t/\eta_t\right)^{-1} \lessgtr 0,~\forall \sigma \gtrless 1
\end{align*}
The sign of the derivative depends on the value of the elasticity of substitution between capital and labor with respect to 1. Finally, the partial derivative of the \(g\) function with respect to \(L_t\), after some simplifications, is:
\begin{align*}
    g_L &= -\frac{1}{N_t^y-L_t} - \frac{1}{\sigma L_t} \left(\frac{\phi}{1-\phi}k_t^{\frac{\sigma-1}{\sigma}}\eta_t - \sigma\right) \\
    g_L &= -\frac{1}{N_t^y-L_t} - \frac{1}{\sigma L_t} \left(\eta_t/\Theta_t - \sigma\right)
\end{align*}
At the equilibrium with unemployment, \(\eta_t/\Theta_t > 1\). \(\eta_t/\Theta_t -\sigma\) is always positive for \(\sigma < 1\), thus \(g_L < 0~\forall \sigma < 1\). However, the sign cannot be deduced without additional assumptions for \(\sigma > 1\). A more restrictive condition is required, i.e.~\(\eta_t/\Theta_t > \sigma\). In such a case, the partial derivative is unambiguously negative. If this condition is not met, \(g_L\) can still be negative provided that the unemployment rate is lower than a threshold \(\bar{u}_t = \left(1 - \frac{\eta_t}{\Theta_t \sigma}\right)^{-1}\). Otherwise, \(g_L\) is positive.

\hypertarget{the-h-functions-derivatives}{%
\subsection{\texorpdfstring{The \(h\) function's derivatives}{The h function's derivatives}}\label{the-h-functions-derivatives}}

\begin{equation*}
    h(L_t, K_t; \sigma, \phi, \gamma) = \left[ \sigma + \frac{1-\phi}{\phi} \frac{1-\gamma(1-\sigma)}{\gamma} \left(\frac{K_t}{L_t}\right)^{\frac{1-\sigma}{\sigma}} \right]^{-1}
\end{equation*}
The partial derivative of the \(h\) function with respect to \(K_t\) is:
\begin{equation*}
    h_K = \frac{1}{K_t}\frac{\sigma-1}{\sigma}\frac{\frac{1-\phi}{\phi}\frac{1-\gamma(1-\sigma)}{\gamma}k_t^{\frac{1-\sigma}{\sigma}}}{\left(\sigma + \frac{1-\phi}{\phi}\frac{1-\gamma(1-\sigma)}{\gamma}k_t^{\frac{1-\sigma}{\sigma}}\right)^2} \gtrless 0,~\forall \sigma \gtrless 1
\end{equation*}
The partial derivative of the \(h\) function with respect to \(L_t\) is:
\begin{equation*}
    h_L = -\frac{1}{L_t}\frac{\sigma-1}{\sigma}\frac{\frac{1-\phi}{\phi}\frac{1-\gamma(1-\sigma)}{\gamma}k_t^{\frac{1-\sigma}{\sigma}}}{\left(\sigma + \frac{1-\phi}{\phi}\frac{1-\gamma(1-\sigma)}{\gamma}k_t^{\frac{1-\sigma}{\sigma}}\right)^2} \lessgtr 0,~\forall \sigma \gtrless 1
\end{equation*}

  \bibliography{lisa.bib}

\end{document}
